import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import { join } from "node:path"
import test from "node:test"
import { PGlite } from "@electric-sql/pglite"

const read = (path: string) => readFileSync(join(process.cwd(), path), "utf8")
const actor = "20000000-0000-4000-8000-000000000002"
const other = "20000000-0000-4000-8000-000000000003"

async function setup() {
  const db = new PGlite()
  await db.exec(read("lib/orders/fixtures/dispatch-schema.sql"))
  await db.exec(read("supabase/migrations/20261005100000_dispatch_operations.sql"))
  await db.exec(read("supabase/migrations/20261005110000_dispatch_guards.sql"))
  await db.exec(`
    alter table dispatch_batches add column prepared_at timestamptz generated always as
      (case when status in ('closed','handed_over') then closed_at else null end) stored;
    alter table ordenes add column usuario_id uuid;
    alter table ordenes add column payment_method_id text default 'transferencia';
    alter table ordenes add column payment_id text;
    alter table ordenes add column andreani_tracking text;
    alter table ordenes add column external_amount_due numeric;
    alter table ordenes add column credit_note_required boolean default false;
    alter table ordenes add column refund_amount numeric;
    alter table ordenes add column refund_method text;
    alter table ordenes add column refunded_at timestamptz;
    alter table ordenes add column refunded_by uuid;
    alter table ordenes add column refund_proof_url text;
    alter table ordenes add column refund_proof_file_name text;
    alter table order_audit_events add column previous_status text;
    alter table order_audit_events add column new_status text;
    create schema storage;
    create table storage.objects(bucket_id text,name text);
    create table order_credit_notes(id uuid primary key default gen_random_uuid(),order_id bigint,
      status text,destination text,total_amount numeric,cae text,settlement_status text,
      management_status text,settlement_date date,settlement_reference text,updated_at timestamptz);
    create table order_refund_proofs(id bigint generated by default as identity primary key,
      order_id bigint,uploaded_by uuid,file_name text not null,file_path text not null,
      mime_type text not null,file_size bigint not null,amount numeric,method text,
      observation text,bank_reference text,refund_date date);
    create table customer_notifications(user_id uuid,type text,title text,body text,action_url text,
      order_id bigint,source_key text unique);
    create table order_claim_units(claim_id bigint);
    create function order_claim_money_block(bigint) returns text language sql as $$ select null::text $$;
    create function assert_order_claim_money_released(bigint) returns void language plpgsql as $$ begin return; end $$;
  `)
  await db.exec(read("supabase/migrations/20261005130000_financial_resolution_orchestrator.sql"))
  await db.exec(read("supabase/migrations/20261005131000_financial_resolution_legacy_guard.sql"))
  await db.exec(read("supabase/migrations/20261005132000_financial_partial_manual_amount.sql"))
  await db.exec(`create trigger aa_guard_claim_refund_proof before insert on order_refund_proofs
    for each row execute function guard_claim_refund_proof();`)
  await db.exec(`create trigger aa_guard_claim_mercadopago_refund
    before insert or update of status on mercadopago_order_refunds
    for each row execute function guard_claim_mercadopago_refund();`)
  await db.query("select set_config('request.jwt.claim.role','service_role',false)")
  await db.query("insert into profiles(id,rol) values ($1,'admin'),($2,'admin')", [actor,other])
  await db.exec("insert into ordenes(id,financial_status,payment_confirmed_amount,payment_method_id,invoice_status) values (1,'refund_pending',15000,'transferencia','none'),(2,'refund_pending',15000,'mercadopago','none')")
  return db
}

test("tanda cerrada marca corte histórico y bloquea MP incluso desde el flujo anterior", async () => {
  const db = await setup()
  try {
    await db.exec(`update ordenes set financial_status='payment_confirmed' where id=2;
      insert into dispatch_batches(id,code,request_key,status,created_by)
      values (1,'DSP-20261005-001','30000000-0000-4000-8000-000000000010','open','${actor}');
      insert into order_packages(id,order_id,status,prepared_by,prepared_at)
      values (1,2,'prepared','${actor}',now());
      insert into dispatch_batch_items(batch_id,package_id,order_id,added_by)
      values (1,1,2,'${actor}');
      update dispatch_batches set status='closed',closed_at=now(),closed_by='${actor}' where id=1;
      update ordenes set financial_status='refund_pending' where id=2;`)
    assert.equal((await db.query<{ prepared: boolean }>("select order_was_prepared_for_dispatch(2) prepared")).rows[0].prepared, true)
    await assert.rejects(db.query("select reserve_order_financial_resolution(2,$1,'mercadopago_refund')", [actor]), /FINANCIAL_PREPARED_MANUAL_ONLY/)
    // El corte no depende de la membresía activa (un retiro posterior conserva el historial).
    await db.exec(`update dispatch_batch_items set removed_at=now()+interval '1 minute',
      removed_by='${actor}',removal_reason='Retirado después del cierre' where order_id=2;`)
    assert.equal((await db.query<{ prepared: boolean }>("select order_was_prepared_for_dispatch(2) prepared")).rows[0].prepared, true)
    await assert.rejects(db.exec("insert into mercadopago_order_refunds(order_id,status) values (2,'processing')"), /REFUND_PREPARED_BATCH/)
  } finally { await db.close() }
})

test("reserva e intento son únicos; segundo administrador no toma el lease", async () => {
  const db = await setup()
  try {
    const first = (await db.query<{ id: string }>("select (reserve_order_financial_resolution(1,$1,'manual_refund')).id id", [actor])).rows[0]
    const again = (await db.query<{ id: string }>("select (reserve_order_financial_resolution(1,$1,'manual_refund')).id id", [other])).rows[0]
    assert.equal(first.id, again.id)
    const key1 = "30000000-0000-4000-8000-000000000001"
    const key2 = "30000000-0000-4000-8000-000000000002"
    const one = (await db.query<{ lease_key: string }>("select (claim_order_financial_resolution($1,$2,$3)).lease_key lease_key", [first.id, actor, key1])).rows[0]
    const two = (await db.query<{ lease_key: string }>("select (claim_order_financial_resolution($1,$2,$3)).lease_key lease_key", [first.id, other, key2])).rows[0]
    assert.equal(one.lease_key, key1)
    assert.equal(two.lease_key, key1)
    assert.equal((await db.query<{ n: number }>("select count(*)::int n from order_financial_resolutions where order_id=1")).rows[0].n, 1)
  } finally { await db.close() }
})

test("reintegro manual acepta comprobante ausente y conserva monto, responsable y referencia", async () => {
  const db = await setup()
  try {
    const id = (await db.query<{ id: string }>("select (reserve_order_financial_resolution(1,$1,'manual_refund')).id id", [actor])).rows[0].id
    await db.query("update order_financial_resolutions set status='manual_pending' where id=$1", [id])
    const completed = (await db.query<{ status: string }>("select (complete_manual_order_financial_refund($1,$2,'TRANSFER-123','Reintegro realizado',null)).status status", [id, actor])).rows[0]
    assert.equal(completed.status, "completed")
    const proof = (await db.query<{ amount: number; bank_reference: string; file_path: string | null; uploaded_by: string }>("select amount,bank_reference,file_path,uploaded_by from order_refund_proofs where order_id=1")).rows[0]
    assert.equal(Number(proof.amount), 15000)
    assert.equal(proof.bank_reference, "TRANSFER-123")
    assert.equal(proof.file_path, null)
    assert.equal(proof.uploaded_by, actor)
    await db.query("select complete_manual_order_financial_refund($1,$2,null,null,null)", [id, other])
    assert.equal((await db.query<{ n: number }>("select count(*)::int n from order_refund_proofs where order_id=1")).rows[0].n, 1)
  } finally { await db.close() }
})

test("entrega a Andreani exige devolución/recepción antes de reservar o completar", async () => {
  const db = await setup()
  try {
    await db.exec(`insert into dispatch_batches(id,code,request_key,status,created_by)
      values (1,'DSP-20261005-001','30000000-0000-4000-8000-000000000010','open','${actor}');
      alter table ordenes disable trigger guard_andreani_handover;
      update ordenes set andreani_handed_over_at=now(),
      andreani_handed_over_batch_id=1,andreani_handed_over_by='${actor}' where id=1;
      alter table ordenes enable trigger guard_andreani_handover;`)
    await assert.rejects(db.query("select reserve_order_financial_resolution(1,$1,'manual_refund')", [actor]), /FINANCIAL_NOT_PENDING/)
  } finally { await db.close() }
})

test("NC ya autorizada se liquida sin emitir otro comprobante", async () => {
  const db = await setup()
  try {
    await db.exec(`update ordenes set invoice_status='authorized' where id=1;
      insert into order_credit_notes(order_id,status,destination,total_amount,cae,settlement_status)
      values (1,'authorized','external_refund',15000,'CAE-EXISTENTE','pendiente');`)
    const id = (await db.query<{ id: string }>("select (reserve_order_financial_resolution(1,$1,'manual_refund')).id id", [actor])).rows[0].id
    await db.query("update order_financial_resolutions set status='manual_pending' where id=$1", [id])
    await db.query("select complete_manual_order_financial_refund($1,$2,null,null,null)", [id, actor])
    const notes = (await db.query<{ count: number; settlement_status: string }>("select count(*)::int count,max(settlement_status) settlement_status from order_credit_notes where order_id=1")).rows[0]
    assert.equal(notes.count, 1)
    assert.equal(notes.settlement_status, "completado")
  } finally { await db.close() }
})

test("flujos antiguos no pueden registrar otro destino después de reservar", async () => {
  const db = await setup()
  try {
    await db.exec(`update ordenes set usuario_id='${actor}' where id=1`)
    await db.query("select reserve_order_financial_resolution(1,$1,'beyonix_credit')", [actor])
    await assert.rejects(db.exec(`insert into order_refund_proofs(order_id,uploaded_by,file_name,file_path,mime_type,file_size,amount,method)
      values (1,'${actor}','c.pdf','payment-proofs/1/c.pdf','application/pdf',100,15000,'Transferencia')`), /FINANCIAL_CHOICE_CONFLICT/)
    await assert.rejects(db.exec("insert into order_credit_notes(order_id,status,destination,total_amount) values (1,'processing','external_refund',15000)"), /FINANCIAL_CHOICE_CONFLICT/)
  } finally { await db.close() }
})

test("una NC con destino distinto impide elegir una resolución incompatible", async () => {
  const db = await setup()
  try {
    await db.exec("insert into order_credit_notes(order_id,status,destination,total_amount,cae) values (1,'authorized','customer_balance',15000,'CAE-EXISTENTE')")
    await assert.rejects(db.query("select reserve_order_financial_resolution(1,$1,'manual_refund')", [actor]), /FINANCIAL_CHOICE_CONFLICT/)
  } finally { await db.close() }
})

test("MP parcial sólo reserva el monto de la NC para reintegro manual", async () => {
  const db = await setup()
  try {
    await db.exec("insert into order_credit_notes(order_id,status,destination,total_amount,cae,settlement_status) values (2,'authorized','external_refund',5000,'CAE-PARCIAL','pendiente')")
    await assert.rejects(db.query("select reserve_order_financial_resolution(2,$1,'mercadopago_refund')", [actor]), /FINANCIAL_MP_INELIGIBLE/)
    const row = (await db.query<{ id: string; amount: number }>("select (r).id,(r).amount from (select reserve_order_financial_resolution(2,$1,'manual_refund') r) s", [actor])).rows[0]
    assert.equal(Number(row.amount), 5000)
    await db.query("update order_financial_resolutions set status='manual_pending' where id=$1", [row.id])
    await db.query("select complete_manual_order_financial_refund($1,$2,null,null,null)", [row.id, actor])
    assert.equal(Number((await db.query<{ amount: number }>("select amount from order_refund_proofs where order_id=2")).rows[0].amount), 5000)
  } finally { await db.close() }
})
