create table if not exists public.producto_variantes (
  id bigint generated by default as identity primary key,
  producto_id bigint not null references public.productos(id) on delete cascade,
  nombre text not null,
  color_hex text not null,
  stock integer,
  activo boolean not null default true,
  orden integer not null default 1,
  created_at timestamptz not null default now(),
  constraint producto_variantes_color_hex_check
    check (color_hex ~ '^#[0-9A-Fa-f]{6}$')
);

create index if not exists producto_variantes_producto_id_idx
  on public.producto_variantes(producto_id);

create index if not exists producto_variantes_orden_idx
  on public.producto_variantes(producto_id, orden);

alter table public.producto_variantes
  add column if not exists imagenes jsonb not null default '[]'::jsonb;

alter table public.producto_variantes enable row level security;

drop policy if exists "producto_variantes_public_select"
  on public.producto_variantes;

drop policy if exists "producto_variantes_admin_select"
  on public.producto_variantes;

drop policy if exists "producto_variantes_admin_insert"
  on public.producto_variantes;

drop policy if exists "producto_variantes_admin_update"
  on public.producto_variantes;

drop policy if exists "producto_variantes_admin_delete"
  on public.producto_variantes;

create policy "producto_variantes_public_select"
  on public.producto_variantes
  for select
  using (activo = true);

create policy "producto_variantes_admin_select"
  on public.producto_variantes
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.profiles
      where profiles.id = auth.uid()
        and profiles.rol = 'admin'
    )
  );

create policy "producto_variantes_admin_insert"
  on public.producto_variantes
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.profiles
      where profiles.id = auth.uid()
        and profiles.rol = 'admin'
    )
  );

create policy "producto_variantes_admin_update"
  on public.producto_variantes
  for update
  to authenticated
  using (
    exists (
      select 1
      from public.profiles
      where profiles.id = auth.uid()
        and profiles.rol = 'admin'
    )
  )
  with check (
    exists (
      select 1
      from public.profiles
      where profiles.id = auth.uid()
        and profiles.rol = 'admin'
    )
  );

create policy "producto_variantes_admin_delete"
  on public.producto_variantes
  for delete
  to authenticated
  using (
    exists (
      select 1
      from public.profiles
      where profiles.id = auth.uid()
        and profiles.rol = 'admin'
    )
  );
