create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  table_name text not null,
  action text not null check (action in ('INSERT', 'UPDATE', 'DELETE')),
  record_id text,
  actor_user_id uuid,
  actor_email text,
  before_data jsonb,
  after_data jsonb,
  created_at timestamptz not null default now(),
  undone_at timestamptz,
  undone_by uuid
);

create index if not exists audit_logs_created_at_idx
  on public.audit_logs(created_at desc);

create index if not exists audit_logs_table_name_idx
  on public.audit_logs(table_name);

alter table public.audit_logs enable row level security;

drop policy if exists "audit_logs_super_admin_select"
  on public.audit_logs;

create policy "audit_logs_super_admin_select"
  on public.audit_logs
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.profiles
      where profiles.id = auth.uid()
        and profiles.rol = 'super_admin'
    )
  );

grant select on public.audit_logs to authenticated;

create or replace function public.audit_log_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor_user_id uuid;
  v_actor_email text;
  v_record_id text;
begin
  if current_setting('app.audit_skip', true) = 'true' then
    if tg_op = 'DELETE' then
      return old;
    end if;

    return new;
  end if;

  v_actor_user_id := auth.uid();

  select profiles.email
    into v_actor_email
  from public.profiles
  where profiles.id = v_actor_user_id;

  v_actor_email := coalesce(v_actor_email, auth.jwt() ->> 'email');

  if tg_op = 'DELETE' then
    v_record_id := old.id::text;
  else
    v_record_id := new.id::text;
  end if;

  insert into public.audit_logs (
    table_name,
    action,
    record_id,
    actor_user_id,
    actor_email,
    before_data,
    after_data
  )
  values (
    tg_table_name,
    tg_op,
    v_record_id,
    v_actor_user_id,
    v_actor_email,
    case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end,
    case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end
  );

  if tg_op = 'DELETE' then
    return old;
  end if;

  return new;
end;
$$;

do $$
begin
  if to_regclass('public.productos') is not null then
    drop trigger if exists productos_audit_log_trigger on public.productos;
    create trigger productos_audit_log_trigger
      after insert or update or delete on public.productos
      for each row execute function public.audit_log_change();
  end if;

  if to_regclass('public.producto_variantes') is not null then
    drop trigger if exists producto_variantes_audit_log_trigger on public.producto_variantes;
    create trigger producto_variantes_audit_log_trigger
      after insert or update or delete on public.producto_variantes
      for each row execute function public.audit_log_change();
  end if;

  if to_regclass('public.categorias') is not null then
    drop trigger if exists categorias_audit_log_trigger on public.categorias;
    create trigger categorias_audit_log_trigger
      after insert or update or delete on public.categorias
      for each row execute function public.audit_log_change();
  end if;

  if to_regclass('public.imagenes_producto') is not null then
    drop trigger if exists imagenes_producto_audit_log_trigger on public.imagenes_producto;
    create trigger imagenes_producto_audit_log_trigger
      after insert or update or delete on public.imagenes_producto
      for each row execute function public.audit_log_change();
  end if;

  if to_regclass('public.ordenes') is not null then
    drop trigger if exists ordenes_audit_log_trigger on public.ordenes;
    create trigger ordenes_audit_log_trigger
      after insert or update or delete on public.ordenes
      for each row execute function public.audit_log_change();
  end if;

  if to_regclass('public.orden_items') is not null then
    drop trigger if exists orden_items_audit_log_trigger on public.orden_items;
    create trigger orden_items_audit_log_trigger
      after insert or update or delete on public.orden_items
      for each row execute function public.audit_log_change();
  end if;
end $$;

create or replace function public.undo_audit_log(p_log_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_log public.audit_logs%rowtype;
  v_is_super_admin boolean;
  v_columns text;
begin
  select exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.rol = 'super_admin'
  )
    into v_is_super_admin;

  if not v_is_super_admin then
    raise exception 'Solo un super_admin puede deshacer cambios.';
  end if;

  select *
    into v_log
  from public.audit_logs
  where id = p_log_id
  for update;

  if not found then
    raise exception 'No existe el registro de auditoria.';
  end if;

  if v_log.undone_at is not null then
    raise exception 'Este cambio ya fue deshecho.';
  end if;

  if v_log.table_name not in (
    'productos',
    'producto_variantes',
    'categorias',
    'imagenes_producto',
    'ordenes',
    'orden_items'
  ) then
    raise exception 'La tabla % no permite deshacer cambios.', v_log.table_name;
  end if;

  perform set_config('app.audit_skip', 'true', true);

  if v_log.action = 'INSERT' then
    execute format(
      'delete from public.%I where id = $1::bigint',
      v_log.table_name
    )
    using v_log.record_id;
  elsif v_log.action = 'DELETE' then
    execute format(
      'insert into public.%I select * from jsonb_populate_record(null::public.%I, $1)',
      v_log.table_name,
      v_log.table_name
    )
    using v_log.before_data;
  elsif v_log.action = 'UPDATE' then
    select string_agg(quote_ident(attname), ', ' order by attnum)
      into v_columns
    from pg_attribute
    where attrelid = format('public.%I', v_log.table_name)::regclass
      and attnum > 0
      and not attisdropped;

    execute format(
      'update public.%I set (%s) = (select %s from jsonb_populate_record(null::public.%I, $1)) where id = $2::bigint',
      v_log.table_name,
      v_columns,
      v_columns,
      v_log.table_name
    )
    using v_log.before_data, v_log.record_id;
  else
    raise exception 'Accion no soportada: %', v_log.action;
  end if;

  update public.audit_logs
    set undone_at = now(),
        undone_by = auth.uid()
  where id = p_log_id;

  return true;
end;
$$;

grant execute on function public.undo_audit_log(bigint) to authenticated;

notify pgrst, 'reload schema';
