-- Reservas temporales de stock para evitar compras simultaneas sin stock.
-- Ejecutar en Supabase SQL Editor despues de 03-producto-variantes.sql.

create table if not exists public.stock_reservations (
  id bigint generated by default as identity primary key,
  session_id text not null,
  user_id uuid null references auth.users(id) on delete set null,
  producto_id bigint not null references public.productos(id) on delete cascade,
  variante_id bigint null references public.producto_variantes(id) on delete cascade,
  quantity integer not null check (quantity > 0),
  status text not null default 'active' check (status in ('active', 'completed', 'released')),
  order_id bigint null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  expires_at timestamptz not null default now() + interval '10 minutes'
);

create index if not exists stock_reservations_active_idx
  on public.stock_reservations (producto_id, variante_id, status, expires_at);

create index if not exists stock_reservations_session_idx
  on public.stock_reservations (session_id, status, expires_at);

alter table public.stock_reservations enable row level security;

drop policy if exists "Users can read own stock reservations" on public.stock_reservations;
create policy "Users can read own stock reservations"
  on public.stock_reservations
  for select
  using (auth.uid() = user_id);

drop policy if exists "Admins can read stock reservations" on public.stock_reservations;
create policy "Admins can read stock reservations"
  on public.stock_reservations
  for select
  using (
    exists (
      select 1
      from public.profiles p
      where p.id = auth.uid()
        and p.rol in ('admin', 'super_admin')
    )
  );

create or replace function public.release_expired_stock_reservations()
returns void
language sql
security definer
set search_path = public
as $$
  update public.stock_reservations
  set
    status = 'released',
    updated_at = now()
  where status = 'active'
    and expires_at <= now();
$$;

create or replace function public.reserve_cart_stock(
  p_session_id text,
  p_items jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  reservation_expires_at timestamptz := now() + interval '10 minutes';
  item record;
  current_stock integer;
  reserved_quantity integer;
  available_quantity integer;
  product_name text;
  variant_name text;
begin
  if nullif(trim(p_session_id), '') is null then
    raise exception 'Sesion de carrito invalida';
  end if;

  if jsonb_typeof(p_items) is distinct from 'array' then
    raise exception 'Items invalidos para reservar stock';
  end if;

  perform public.release_expired_stock_reservations();

  update public.stock_reservations
  set
    status = 'released',
    updated_at = now()
  where session_id = p_session_id
    and status = 'active';

  for item in
    select
      (value->>'productId')::bigint as producto_id,
      nullif(value->>'variantId', '')::bigint as variante_id,
      sum((value->>'quantity')::integer) as quantity
    from jsonb_array_elements(p_items)
    where (value->>'productId') is not null
      and (value->>'quantity') is not null
      and (value->>'quantity')::integer > 0
    group by
      (value->>'productId')::bigint,
      nullif(value->>'variantId', '')::bigint
  loop
    if item.variante_id is not null then
      select
        pv.stock,
        pv.nombre,
        p.nombre
      into current_stock, variant_name, product_name
      from public.producto_variantes pv
      join public.productos p on p.id = pv.producto_id
      where pv.id = item.variante_id
        and pv.producto_id = item.producto_id
        and pv.activo = true
      for update of pv;

      if current_stock is null then
        raise exception 'La variante seleccionada no esta disponible';
      end if;

      select coalesce(sum(quantity), 0)
      into reserved_quantity
      from public.stock_reservations
      where status = 'active'
        and expires_at > now()
        and producto_id = item.producto_id
        and variante_id = item.variante_id
        and session_id <> p_session_id;

      available_quantity := greatest(current_stock - reserved_quantity, 0);

      if item.quantity > available_quantity then
        raise exception 'Stock insuficiente para % (%). Disponible: %',
          product_name,
          variant_name,
          available_quantity;
      end if;
    else
      select
        stock,
        nombre
      into current_stock, product_name
      from public.productos
      where id = item.producto_id
        and activo = true
      for update;

      if current_stock is null then
        raise exception 'El producto seleccionado no esta disponible';
      end if;

      select coalesce(sum(quantity), 0)
      into reserved_quantity
      from public.stock_reservations
      where status = 'active'
        and expires_at > now()
        and producto_id = item.producto_id
        and variante_id is null
        and session_id <> p_session_id;

      available_quantity := greatest(current_stock - reserved_quantity, 0);

      if item.quantity > available_quantity then
        raise exception 'Stock insuficiente para %. Disponible: %',
          product_name,
          available_quantity;
      end if;
    end if;

    insert into public.stock_reservations (
      session_id,
      user_id,
      producto_id,
      variante_id,
      quantity,
      status,
      expires_at
    )
    values (
      p_session_id,
      auth.uid(),
      item.producto_id,
      item.variante_id,
      item.quantity,
      'active',
      reservation_expires_at
    );
  end loop;

  return jsonb_build_object(
    'success', true,
    'expires_at', reservation_expires_at
  );
end;
$$;

create or replace function public.complete_cart_stock_reservation(
  p_session_id text,
  p_order_id bigint
)
returns void
language sql
security definer
set search_path = public
as $$
  update public.stock_reservations
  set
    status = 'completed',
    order_id = p_order_id,
    updated_at = now()
  where session_id = p_session_id
    and status = 'active';
$$;

create or replace function public.release_cart_stock_reservation(
  p_session_id text
)
returns void
language sql
security definer
set search_path = public
as $$
  update public.stock_reservations
  set
    status = 'released',
    updated_at = now()
  where session_id = p_session_id
    and status = 'active';
$$;

grant execute on function public.reserve_cart_stock(text, jsonb) to anon, authenticated;
grant execute on function public.complete_cart_stock_reservation(text, bigint) to anon, authenticated;
grant execute on function public.release_cart_stock_reservation(text) to anon, authenticated;
grant execute on function public.release_expired_stock_reservations() to anon, authenticated;
