-- Esquema aislado para ejercitar, con PostgreSQL real (PGlite), la carrera
-- entre creación de envío Andreani y los 3 caminos reales de cancelación
-- (cliente, aprobación de claim, admin directo). Sin red, credenciales ni
-- datos productivos. Sólo las columnas/tablas que esas 4 RPCs realmente
-- leen o escriben -- ninguna de las 4 consulta `profiles`/`auth.users`
-- (reciben el rol/actor ya resuelto por parámetro), así que este fixture no
-- las necesita.

create role anon;
create role authenticated;
create role service_role bypassrls;

create schema auth;
create function auth.role() returns text language sql stable as $$
  select nullif(current_setting('request.jwt.claim.role', true), '')
$$;

create table public.site_settings (
  key text primary key,
  value jsonb,
  description text
);

create table public.ordenes (
  id bigint primary key,
  usuario_id uuid,
  estado text,
  payment_status text,
  payment_proof_url text,
  financial_status text,
  paid_at timestamptz,
  payment_confirmed_amount numeric,
  credit_balance_used numeric not null default 0,
  invoice_status text,
  invoice_cae text,
  invoice_number integer,
  invoice_point integer,
  tracking_number text,
  shipping_provider text,
  envio_proveedor text,
  shipping_type text,
  andreani_tracking text,
  andreani_envio_id text,
  andreani_estado text,
  andreani_etiqueta_url text,
  andreani_contrato text,
  andreani_created_at timestamptz,
  andreani_creation_status text,
  andreani_creation_claim_token uuid,
  andreani_creation_claimed_at timestamptz,
  andreani_creation_environment text,
  andreani_creation_attempts integer default 0,
  andreani_error text,
  cancelled_at timestamptz,
  cancellation_requested_at timestamptz,
  cancellation_requested_by uuid,
  refund_pending_at timestamptz,
  credit_note_required boolean
);

create table public.orden_items (
  id bigint generated by default as identity primary key,
  orden_id bigint references public.ordenes(id),
  cantidad integer
);

create table public.order_claims (
  id bigint generated by default as identity primary key,
  order_id bigint references public.ordenes(id),
  user_id uuid,
  claim_type text not null,
  status text not null default 'recibido',
  failure_type text,
  description text not null,
  affected_items jsonb not null default '[]',
  admin_needs_action boolean default false,
  admin_response text,
  resolution text,
  offered_resolutions jsonb default '[]'::jsonb,
  started_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  closed_at timestamptz,
  last_customer_message_at timestamptz
);

create table public.order_claim_messages (
  id bigint generated by default as identity primary key,
  claim_id bigint references public.order_claims(id),
  author_user_id uuid,
  author_role text,
  message text,
  created_at timestamptz default now()
);

create table public.order_audit_events (
  id bigint generated always as identity primary key,
  order_id bigint,
  actor_type text,
  actor_id uuid,
  action text,
  previous_status text,
  new_status text,
  metadata jsonb,
  created_at timestamptz not null default now()
);

grant usage on schema public, auth to service_role;
grant all privileges on all tables in schema public to service_role;
