-- Fixture aislado para la facturación automática ARCA (20260927100000).
-- Columnas reales de public.ordenes que usa la migración; el resto de la
-- tabla de producción no participa. inventory_order_consumes_stock se carga
-- desde su migración real (ver el test).

do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then create role anon; end if;
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then create role authenticated; end if;
  if not exists (select 1 from pg_roles where rolname = 'service_role') then create role service_role bypassrls; end if;
end;
$$;

create schema if not exists auth;
create or replace function auth.role() returns text language sql stable as $$
  select nullif(current_setting('request.jwt.claim.role', true), '')
$$;
grant usage on schema public, auth to anon, authenticated, service_role;

create table public.ordenes (
  id bigint generated by default as identity primary key,
  estado text not null default 'pendiente',
  payment_status text,
  financial_status text default 'pending_payment',
  payment_method_id text,
  total numeric,
  cancelled_at timestamptz,
  cancellation_requested_at timestamptz,
  order_change_status text,
  credit_note_required boolean not null default false,
  invoice_number bigint,
  invoice_point integer,
  invoice_cae text,
  invoice_cae_due date,
  invoice_status text,
  invoice_error text,
  invoice_created_at timestamptz
);

-- Sólo lo que toca la migración de ambientes (20260927120000); las NC se
-- prueban con su propio fixture.
create table public.order_credit_notes (
  id uuid primary key default gen_random_uuid(),
  order_id bigint not null references public.ordenes(id),
  voucher_point integer,
  voucher_number bigint,
  cae text
);

create table public.order_audit_events (
  id bigint generated always as identity primary key,
  order_id bigint,
  actor_type text,
  actor_id uuid,
  action text,
  previous_status text,
  new_status text,
  metadata jsonb,
  created_at timestamptz not null default now()
);

grant all privileges on public.ordenes, public.order_credit_notes, public.order_audit_events to service_role;
grant usage, select on all sequences in schema public to service_role;

-- RPC heredada tal como está en producción (baseline 2026-09-21): la
-- migración nueva debe revocarla de anon/authenticated.
create function public.begin_arca_invoice_processing(p_order_id bigint)
returns table(id bigint) language plpgsql security definer set search_path = public as $$
begin
  return query select p_order_id;
end;
$$;
grant all on function public.begin_arca_invoice_processing(bigint) to anon, authenticated, service_role;
