-- Esquema aislado para ejecutar funciones con PostgreSQL (PGlite).
-- Sin credenciales, datos productivos ni efectos externos.
create role anon; create role authenticated; create role service_role bypassrls;
create schema auth; create schema storage;
create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
create function auth.role() returns text language sql as $$ select nullif(current_setting('request.jwt.claim.role',true),'') $$;
create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);
create table profiles(id uuid primary key references auth.users(id),email text unique,rol text not null default 'cliente');
create function is_current_user_internal() returns boolean language sql security definer set search_path=public as $$ select coalesce((select rol in ('operador','admin','super_admin') from profiles where id=auth.uid()),false) $$;
create table ordenes(id bigint primary key,usuario_id uuid,cliente_email text,estado text,delivered_at timestamptz,total numeric default 100,
tracking_number text,andreani_tracking text,andreani_envio_id text,andreani_estado text,invoice_status text,invoice_cae text,invoice_number integer,invoice_point integer,paid_at timestamptz,payment_status text,credit_balance_used numeric default 0,cancelled_at timestamptz,cancellation_requested_at timestamptz,cancellation_requested_by uuid,refund_pending_at timestamptz,
financial_status text,credit_note_required boolean,credit_note_amount numeric,refund_proof_url text,refund_proof_file_name text,
refund_proof_mime_type text,refund_proof_file_size bigint,refund_amount numeric,refund_method text,refund_uploaded_by uuid,
refund_uploaded_at timestamptz,refunded_at timestamptz,refunded_by uuid);
create table orden_items(id bigint primary key,orden_id bigint references ordenes(id),cantidad integer,
return_inventory_processed_at timestamptz,return_inventory_processed_by uuid,return_restocked_quantity integer,return_written_off_quantity integer);
create table order_claims(id bigint generated by default as identity primary key,order_id bigint references ordenes(id),user_id uuid references auth.users(id),
claim_type text not null,status text not null default 'recibido',failure_type text,description text not null,
affected_items jsonb not null default '[]',admin_needs_action boolean default false,
admin_response text,rejection_reason text,resolution text,offered_resolutions text[] default '{}',
created_at timestamptz not null default now(),updated_at timestamptz not null default now(),closed_at timestamptz,
last_customer_message_at timestamptz,last_admin_response_at timestamptz,
first_reviewed_at timestamptz,first_reviewed_by uuid,affected_items_updated_at timestamptz,affected_items_updated_by uuid,
check(status in ('recibido','en_revision','falta_informacion','aprobado','reintegro_pendiente','cambio_pendiente','cupon_pendiente','reemplazo_enviado','rechazado','cerrado')),
check(resolution is null or resolution in ('cambio_producto','envio_unidad_faltante','reintegro_total','reintegro_parcial','saldo_a_favor','cupon_descuento','rechazado','otro')));
create unique index order_claims_one_active_per_order_idx on order_claims(order_id) where status not in ('cerrado','rechazado');
create table order_claim_messages(id bigint generated by default as identity primary key,claim_id bigint references order_claims(id),author_user_id uuid references auth.users(id),author_role text,message text,created_at timestamptz default now());
create table order_claim_files(id bigint generated by default as identity primary key,claim_id bigint references order_claims(id),uploaded_by uuid references auth.users(id),file_role text,file_name text,file_path text,mime_type text,file_size bigint,created_at timestamptz default now());
create table order_audit_events(id bigint generated by default as identity primary key,order_id bigint,actor_type text,actor_id uuid,action text,previous_status text,new_status text,metadata jsonb,created_at timestamptz default now());
create table order_credit_notes(id uuid primary key default gen_random_uuid(),order_id bigint,claim_id bigint,status text default 'processing',destination text,cae text,total_amount numeric,settlement_status text default 'pendiente',management_status text,settlement_date date,settlement_reference text,updated_at timestamptz,
reason text,items_amount numeric,manual_amount numeric,invoice_point integer,invoice_number bigint,created_by uuid,operation_type text);
create unique index order_credit_notes_single_processing on order_credit_notes(order_id) where status='processing';
create table order_credit_note_items(credit_note_id uuid,order_item_id bigint,quantity integer,unit_amount numeric,total_amount numeric,product_name text,variant_name text);
create table order_refund_proofs(id bigint generated by default as identity primary key,order_id bigint,uploaded_by uuid,file_name text,file_path text,mime_type text,file_size bigint,amount numeric,method text);
create table customer_credit_movements(id bigint generated by default as identity,order_id bigint,claim_id bigint,source_type text,movement_type text);
create table customer_notifications(user_id uuid,type text,title text,body text,action_url text,order_id bigint,source_key text unique);
create table storage.buckets(id text primary key,public boolean,file_size_limit bigint,allowed_mime_types text[]);
insert into storage.buckets values('order-claim-evidence',false,null,null);
create table storage.objects(bucket_id text,name text,primary key(bucket_id,name));
create function touch_order_claim_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
create trigger touch_order_claim_updated_at_trigger before update on order_claims for each row execute function touch_order_claim_updated_at();
create function sync_order_claim_admin_attention() returns trigger language plpgsql as $$ begin
 if new.author_role='cliente' then update order_claims set admin_needs_action=true,last_customer_message_at=new.created_at where id=new.claim_id and status not in ('cerrado','rechazado');
 else update order_claims set admin_needs_action=false,last_admin_response_at=new.created_at where id=new.claim_id; end if; return new; end $$;
create trigger sync_order_claim_admin_attention_trigger after insert on order_claim_messages for each row execute function sync_order_claim_admin_attention();
create function clear_resolved_order_claim_attention() returns trigger language plpgsql as $$ begin if new.status in ('aprobado','cerrado','rechazado') then new.admin_needs_action=false; end if; return new; end $$;
create trigger clear_resolved_order_claim_attention_trigger before update on order_claims for each row execute function clear_resolved_order_claim_attention();
