-- Esquema aislado para ejecutar la logística de reclamos con PostgreSQL
-- (PGlite): la cadena REAL de migraciones de reclamos más el motor REAL de
-- stock (recepción de devoluciones, ajustes idempotentes, reemplazos). Une
-- claim-schema.sql y return-reception-schema.sql. Sin credenciales, datos
-- productivos ni efectos externos.
create role anon; create role authenticated; create role service_role bypassrls;
create schema auth; create schema storage;
create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
create function auth.role() returns text language sql as $$ select nullif(current_setting('request.jwt.claim.role',true),'') $$;
create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);
create table profiles(id uuid primary key references auth.users(id),email text unique,rol text not null default 'cliente');
create function current_user_role() returns text language sql stable as $$ select rol from public.profiles where id = auth.uid() $$;
create function is_current_user_internal() returns boolean language sql security definer set search_path=public as $$ select coalesce((select rol in ('operador','admin','super_admin') from profiles where id=auth.uid()),false) $$;

create table productos(id bigint generated by default as identity primary key,activo boolean not null default true,stock integer not null default 0);
create table producto_variantes(id bigint generated by default as identity primary key,producto_id bigint not null references productos(id),activo boolean not null default true,stock integer not null default 0);

create table ordenes(id bigint primary key,usuario_id uuid,cliente_email text,estado text,delivered_at timestamptz,total numeric default 100,
tracking_number text,andreani_tracking text,andreani_envio_id text,andreani_estado text,invoice_status text,invoice_cae text,invoice_number integer,invoice_point integer,paid_at timestamptz,payment_status text,credit_balance_used numeric default 0,external_amount_due numeric,payment_confirmed_amount numeric,cancelled_at timestamptz,cancellation_requested_at timestamptz,cancellation_requested_by uuid,refund_pending_at timestamptz,
financial_status text,credit_note_required boolean,credit_note_amount numeric,refund_proof_url text,refund_proof_file_name text,
refund_proof_mime_type text,refund_proof_file_size bigint,refund_amount numeric,refund_method text,refund_uploaded_by uuid,
refund_uploaded_at timestamptz,refunded_at timestamptz,refunded_by uuid,created_at timestamptz not null default now(),
shipping_type text,andreani_sucursal_id text,andreani_sucursal_nombre text,
payment_method_id text,payment_id text,original_total numeric);
create table orden_items(id bigint primary key,orden_id bigint references ordenes(id),producto_id bigint references productos(id),variante_id bigint references producto_variantes(id),
cantidad integer,precio numeric(12,2) not null default 0,return_restocked_quantity integer not null default 0,return_written_off_quantity integer not null default 0,
return_inventory_note text,return_inventory_processed_at timestamptz,return_inventory_processed_by uuid);
create table order_claims(id bigint generated by default as identity primary key,order_id bigint references ordenes(id),user_id uuid references auth.users(id),
claim_type text not null,status text not null default 'recibido',failure_type text,description text not null,
affected_items jsonb not null default '[]',admin_needs_action boolean default false,
admin_response text,rejection_reason text,resolution text,offered_resolutions text[] default '{}',
replacement_shipping_company text,replacement_tracking text,replacement_sent_at timestamptz,
created_at timestamptz not null default now(),updated_at timestamptz not null default now(),closed_at timestamptz,
last_customer_message_at timestamptz,last_admin_response_at timestamptz,
first_reviewed_at timestamptz,first_reviewed_by uuid,affected_items_updated_at timestamptz,affected_items_updated_by uuid,
check(status in ('recibido','en_revision','falta_informacion','aprobado','reintegro_pendiente','cambio_pendiente','cupon_pendiente','reemplazo_enviado','rechazado','cerrado')),
check(resolution is null or resolution in ('cambio_producto','envio_unidad_faltante','reintegro_total','reintegro_parcial','saldo_a_favor','cupon_descuento','rechazado','otro')));
create unique index order_claims_one_active_per_order_idx on order_claims(order_id) where status not in ('cerrado','rechazado');
create table order_claim_messages(id bigint generated by default as identity primary key,claim_id bigint references order_claims(id),author_user_id uuid references auth.users(id),author_role text,message text,created_at timestamptz default now());
create table order_claim_files(id bigint generated by default as identity primary key,claim_id bigint references order_claims(id),uploaded_by uuid references auth.users(id),file_role text,file_name text,file_path text,mime_type text,file_size bigint,created_at timestamptz default now());
create table order_audit_events(id bigint generated by default as identity primary key,order_id bigint,actor_type text,actor_id uuid,action text,previous_status text,new_status text,metadata jsonb,created_at timestamptz default now());
create table order_credit_notes(id uuid primary key default gen_random_uuid(),order_id bigint,claim_id bigint,status text default 'processing',destination text,cae text,total_amount numeric,settlement_status text default 'pendiente',management_status text,settlement_date date,settlement_reference text,updated_at timestamptz,
reason text,items_amount numeric,manual_amount numeric,invoice_point integer,invoice_number bigint,created_by uuid,operation_type text);
create unique index order_credit_notes_single_processing on order_credit_notes(order_id) where status='processing';
create table order_credit_note_items(credit_note_id uuid,order_item_id bigint,quantity integer,unit_amount numeric,total_amount numeric,product_name text,variant_name text);
create table order_refund_proofs(id bigint generated by default as identity primary key,order_id bigint,uploaded_by uuid,file_name text,file_path text,mime_type text,file_size bigint,amount numeric,method text);
create table customer_credit_movements(id bigint generated by default as identity,order_id bigint,claim_id bigint,source_type text,movement_type text);
create table customer_notifications(id uuid primary key default gen_random_uuid(),user_id uuid,type text,title text,body text,action_url text,order_id bigint,source_key text unique,
is_read boolean not null default false,created_at timestamptz not null default now(),dismissed_at timestamptz);
create table storage.buckets(id text primary key,public boolean,file_size_limit bigint,allowed_mime_types text[]);
insert into storage.buckets values('order-claim-evidence',false,null,null);
create table storage.objects(bucket_id text,name text,primary key(bucket_id,name));
create function touch_order_claim_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=clock_timestamp(); return new; end $$;
create trigger touch_order_claim_updated_at_trigger before update on order_claims for each row execute function touch_order_claim_updated_at();
-- Igual a producción (baseline 2026-09-21).
create function sync_order_claim_admin_attention() returns trigger language plpgsql as $$ begin
 if new.author_role='cliente' then update order_claims set admin_needs_action=true,last_customer_message_at=new.created_at where id=new.claim_id and status not in ('cerrado','rechazado');
 else update order_claims set admin_needs_action=false,last_admin_response_at=new.created_at where id=new.claim_id; end if; return new; end $$;
create trigger sync_order_claim_admin_attention_trigger after insert on order_claim_messages for each row execute function sync_order_claim_admin_attention();
create function clear_resolved_order_claim_attention() returns trigger language plpgsql as $$ begin if new.status in ('cerrado','rechazado') then new.admin_needs_action=false; end if; return new; end $$;
create trigger clear_resolved_order_claim_attention_trigger before insert or update of status on order_claims for each row execute function clear_resolved_order_claim_attention();

-- Motor de stock (idéntico a return-reception-schema.sql).
create table public.audit_logs(id bigint generated always as identity primary key,table_name text,action text,record_id text,actor_user_id uuid,actor_email text,before_data jsonb,after_data jsonb,created_at timestamptz not null default now());
create or replace function public.audit_log_change() returns trigger language plpgsql security definer set search_path to 'public' as $$
declare v_actor uuid := auth.uid(); v_email text;
begin
  select email into v_email from public.profiles where id = v_actor;
  insert into public.audit_logs(table_name, action, record_id, actor_user_id, actor_email, before_data, after_data)
  values (tg_table_name, tg_op, case when tg_op = 'DELETE' then old.id::text else new.id::text end, v_actor, v_email,
    case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) end, case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) end);
  if tg_op = 'DELETE' then return old; end if;
  return new;
end $$;
create table public.mercadolibre_sales(id uuid primary key default gen_random_uuid(),sale_date timestamptz not null default now(),product_id bigint references public.productos(id),quantity integer not null default 1,raw_data jsonb not null default '{}'::jsonb);
create function public.inventory_ml_variant_id(p_raw_data jsonb) returns bigint language sql immutable as $$ select nullif(p_raw_data->'beyonix_cost_mapping'->>'variant_id', '')::bigint $$;
create table public.catalog_sku_registry(normalized_sku text primary key,product_id bigint,variant_id bigint,conditioned_stock_id uuid);
create function public.normalized_catalog_sku(p_sku text) returns text language sql immutable as $$ select nullif(upper(btrim(coalesce(p_sku, ''))), '') $$;
create or replace function public.refresh_inventory_from_row() returns trigger language plpgsql security definer set search_path to 'public' as $$
begin
  if tg_op <> 'INSERT' and old.product_id is not null then perform public.refresh_inventory_stock(old.product_id); end if;
  if tg_op <> 'DELETE' and new.product_id is not null and (tg_op = 'INSERT' or new.product_id is distinct from old.product_id) then
    perform public.refresh_inventory_stock(new.product_id);
  end if;
  return case when tg_op = 'DELETE' then old else new end;
end $$;
create table public.inventory_stock_adjustments(id uuid primary key default gen_random_uuid(),product_id bigint not null references public.productos(id),variant_id bigint not null references public.producto_variantes(id),quantity_delta integer not null,reason text not null,created_by uuid,created_at timestamptz not null default now(),idempotency_key text);
create table public.inventory_operation_log(id uuid primary key default gen_random_uuid(),product_id bigint not null,variant_id bigint,movement_type text not null,quantity integer not null,origin text not null,effective_at timestamptz not null,actor_user_id uuid,actor_process text not null,idempotency_key text not null unique,source_table text not null,source_id text not null,document_reference text not null,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create function public.refresh_inventory_stock(p_product_id bigint) returns void language plpgsql as $$
begin
  perform set_config('beyonix.inventory_refresh', 'on', true);
  update public.producto_variantes v
  set stock = coalesce((select sum(m.sellable_quantity) from public.inventory_return_movements m where m.variant_id = v.id), 0)
    + coalesce((select sum(a.quantity_delta) from public.inventory_stock_adjustments a where a.variant_id = v.id), 0)
  where v.producto_id = p_product_id;
end $$;
create or replace function public.adjust_variant_stock_idempotent(p_variant_id bigint, p_new_quantity integer, p_reason text, p_actor_id uuid, p_idempotency_key text)
returns producto_variantes language plpgsql security definer set search_path to 'public' as $function$
declare
  v_variant public.producto_variantes%rowtype;
  v_reason text := nullif(btrim(coalesce(p_reason, '')), '');
  v_key text := nullif(btrim(coalesce(p_idempotency_key, '')), '');
  v_delta integer;
begin
  if v_key is null or length(v_key) < 8 or length(v_key) > 240 then raise exception 'IDEMPOTENCY_KEY_INVALID'; end if;
  if p_new_quantity is null or p_new_quantity < 0 then raise exception 'La cantidad no puede ser negativa.'; end if;
  if v_reason is null or length(v_reason) < 3 then raise exception 'Indicá un motivo para el ajuste.'; end if;
  perform pg_advisory_xact_lock(hashtext('inventory-stock-adjustment'), hashtext(v_key));
  if exists (select 1 from public.inventory_operation_log log where log.idempotency_key = v_key) then
    select * into v_variant from public.producto_variantes where id = p_variant_id;
    return v_variant;
  end if;
  select * into v_variant from public.producto_variantes where id = p_variant_id for update;
  if not found then raise exception 'La variante ya no existe.'; end if;
  perform pg_advisory_xact_lock(93000, v_variant.producto_id::integer);
  v_delta := p_new_quantity - coalesce(v_variant.stock, 0);
  if v_delta = 0 then return v_variant; end if;
  insert into public.inventory_stock_adjustments(product_id, variant_id, quantity_delta, reason, created_by, idempotency_key)
  values (v_variant.producto_id, p_variant_id, v_delta, v_reason, p_actor_id, v_key);
  perform public.refresh_inventory_stock(v_variant.producto_id);
  insert into public.inventory_operation_log(product_id, variant_id, movement_type, quantity, origin, effective_at, actor_user_id, actor_process, idempotency_key, source_table, source_id, document_reference, metadata)
  values (v_variant.producto_id, p_variant_id, 'adjustment', abs(v_delta), 'admin_stock_adjustment', now(), p_actor_id, 'adjust_variant_stock_idempotent', v_key, 'inventory_stock_adjustments', v_key, v_reason,
    jsonb_build_object('previousStock', coalesce(v_variant.stock, 0), 'newStock', p_new_quantity, 'delta', v_delta))
  on conflict (idempotency_key) do nothing;
  select * into v_variant from public.producto_variantes where id = p_variant_id;
  return v_variant;
end;
$function$;
create or replace function public.compute_historical_unit_cost(p_product_id bigint, p_variant_id bigint, p_as_of date)
returns numeric language sql stable as $$ select 500::numeric $$;
