create role anon;
create role authenticated;
create role service_role bypassrls;
create schema auth;
create function auth.role() returns text language sql stable as $$
  select nullif(current_setting('request.jwt.claim.role', true), '')
$$;
create table public.profiles (id uuid primary key, rol text not null);
create table public.ordenes (
  id bigint primary key,
  estado text default 'pagado',
  cancelled_at timestamptz,
  payment_status text default 'confirmado',
  paid_at timestamptz default now(),
  payment_confirmed_amount numeric default 10000,
  financial_status text default 'payment_confirmed',
  invoice_status text default 'authorized',
  invoice_cae text default 'CAE-TEST',
  order_change_status text,
  return_status text,
  return_resolved_at timestamptz,
  shipping_provider text default 'andreani',
  envio_proveedor text,
  andreani_envio_id text default 'AND-TEST',
  andreani_creation_status text default 'created',
  andreani_estado text,
  andreani_tracking_event_at timestamptz,
  tracking_number text
);
create table public.productos (id bigint primary key, sku text, codigo_barra text, nombre text);
create table public.producto_variantes (
  id bigint primary key, producto_id bigint references public.productos(id),
  sku text, codigo_barra text
);
create table public.catalog_sku_registry (
  normalized_sku text primary key, product_id bigint, variant_id bigint
);
create function public.is_current_user_internal() returns boolean
language sql stable as $$ select false $$;
create table public.orden_items (
  id bigint primary key,
  orden_id bigint references public.ordenes(id),
  producto_id bigint references public.productos(id),
  variante_id bigint references public.producto_variantes(id),
  conditioned_stock_id uuid,
  conditioned_sku text,
  cantidad integer not null
);
create table public.order_claims (
  id bigint generated by default as identity primary key,
  order_id bigint references public.ordenes(id),
  status text default 'recibido',
  failure_type text default 'producto_defectuoso',
  cancelled_at timestamptz
);
create table public.mercadopago_order_refunds (
  id bigint generated by default as identity primary key,
  order_id bigint references public.ordenes(id),
  status text not null
);
create table public.order_audit_events (
  id bigint generated by default as identity primary key,
  order_id bigint,
  actor_type text,
  actor_id uuid,
  action text,
  metadata jsonb,
  created_at timestamptz default now()
);
create function public.normalized_catalog_sku(p_value text) returns text
language sql immutable as $$ select nullif(upper(btrim(p_value)), '') $$;
