-- Esquema aislado para ejecutar la migración 20260913120000 con PostgreSQL
-- real (PGlite). Sin credenciales, datos productivos ni efectos externos.
-- Sólo las columnas que la migración NO agrega -- el resto (transfer_*) las
-- crea la propia migración bajo test, igual que contra la base real.
create role anon; create role authenticated; create role service_role bypassrls;
create schema auth;
create function auth.role() returns text language sql as $$ select nullif(current_setting('request.jwt.claim.role',true),'') $$;

create table ordenes(
  id bigint primary key,
  usuario_id uuid,
  cliente_email text,
  cliente_nombre text,
  estado text not null default 'pendiente',
  payment_method_id text,
  payment_status text,
  financial_status text,
  total numeric,
  external_amount_due numeric,
  paid_at timestamptz,
  payment_confirmed_by uuid,
  payment_confirmed_at timestamptz,
  payment_confirmed_amount numeric,
  order_change_status text,
  order_change_extra_amount numeric,
  cancelled_at timestamptz
);

create table order_audit_events(
  id bigint generated by default as identity primary key,
  order_id bigint,
  actor_type text,
  actor_id uuid,
  action text,
  previous_status text,
  new_status text,
  metadata jsonb,
  created_at timestamptz default now()
);
