-- Esquema aislado para ejecutar la migración 20260913120000 con PostgreSQL
-- real (PGlite). Sin credenciales, datos productivos ni efectos externos.
-- Sólo las columnas que la migración NO agrega -- el resto (transfer_*) las
-- crea la propia migración bajo test, igual que contra la base real.
create role anon; create role authenticated; create role service_role bypassrls;
create schema auth;
create function auth.role() returns text language sql as $$ select nullif(current_setting('request.jwt.claim.role',true),'') $$;

create table ordenes(
  id bigint primary key,
  usuario_id uuid,
  cliente_email text,
  cliente_nombre text,
  created_at timestamptz not null default now(),
  estado text not null default 'pendiente',
  payment_method_id text,
  payment_status text,
  financial_status text,
  total numeric,
  external_amount_due numeric,
  paid_at timestamptz,
  payment_confirmed_by uuid,
  payment_confirmed_at timestamptz,
  payment_confirmed_amount numeric,
  order_change_status text,
  order_change_extra_amount numeric,
  cancelled_at timestamptz
);

create table order_audit_events(
  id bigint generated by default as identity primary key,
  order_id bigint,
  actor_type text,
  actor_id uuid,
  action text,
  previous_status text,
  new_status text,
  metadata jsonb,
  created_at timestamptz default now()
);

-- Simulación mínima (NO el trigger real) del guardián de inventario
-- (validate_inventory_order_confirmation, 20260904090000): sólo existe para
-- poder probar, contra PostgreSQL real, que confirm_transfer_auto_verification
-- reclama transfer_matched_payment_id de forma atómica cuando la
-- confirmación completa es rechazada por falta de stock. Se activa
-- explícitamente por test vía set_config('test.simulate_stock_conflict', '1', false)
-- y sólo dispara cuando la fila transiciona a estado='pagado' -- igual
-- criterio de "sólo al entrar a un estado que consume stock" que
-- inventory_order_consumes_stock, sin reimplementar esa función completa.
create or replace function simulate_stock_guard() returns trigger language plpgsql as $$
begin
  if new.estado = 'pagado'
     and coalesce(current_setting('test.simulate_stock_conflict', true), '') = '1' then
    raise exception 'CHECKOUT_STOCK_INSUFFICIENT';
  end if;
  return new;
end;
$$;

create trigger simulate_stock_guard
before update of estado, payment_status on ordenes
for each row execute function simulate_stock_guard();
