alter table public.profiles
  add column if not exists rol text not null default 'cliente';

update public.profiles
set rol = 'cliente'
where rol is null
   or rol not in ('cliente', 'operador', 'admin', 'super_admin');

alter table public.profiles
  drop constraint if exists profiles_rol_check;

alter table public.profiles
  add constraint profiles_rol_check
  check (rol in ('cliente', 'operador', 'admin', 'super_admin'));

update public.profiles
set rol = 'super_admin'
where lower(email) = 'espinosatrabajo@gmail.com';

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  table_name text not null,
  action text not null check (action in ('INSERT', 'UPDATE', 'DELETE')),
  record_id text,
  actor_user_id uuid references auth.users(id) on delete set null,
  actor_email text,
  before_data jsonb,
  after_data jsonb,
  created_at timestamptz not null default now(),
  undone_at timestamptz,
  undone_by uuid references auth.users(id) on delete set null
);

create or replace function public.current_user_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select rol
  from public.profiles
  where id = auth.uid();
$$;

revoke all on function public.current_user_role() from public;
grant execute on function public.current_user_role() to authenticated;

create or replace function public.is_current_user_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_user_role() in ('admin', 'super_admin'), false);
$$;

create or replace function public.is_current_user_internal()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    public.current_user_role() in ('operador', 'admin', 'super_admin'),
    false
  );
$$;

revoke all on function public.is_current_user_admin() from public;
revoke all on function public.is_current_user_internal() from public;
grant execute on function public.is_current_user_admin() to authenticated;
grant execute on function public.is_current_user_internal() to authenticated;

create or replace function public.protect_primary_super_admin()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'UPDATE'
     and lower(old.email) = 'espinosatrabajo@gmail.com'
     and (
       new.rol is distinct from 'super_admin'
       or lower(coalesce(new.email, '')) is distinct from
          'espinosatrabajo@gmail.com'
     ) then
    raise exception 'El super administrador principal está protegido.';
  end if;

  if lower(coalesce(new.email, '')) = 'espinosatrabajo@gmail.com' then
    new.rol := 'super_admin';
  end if;

  return new;
end;
$$;

drop trigger if exists protect_primary_super_admin on public.profiles;
create trigger protect_primary_super_admin
before insert or update on public.profiles
for each row execute function public.protect_primary_super_admin();

create or replace function public.protect_profile_role_changes()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_role text;
begin
  if new.rol is not distinct from old.rol then
    return new;
  end if;

  if auth.role() = 'service_role' then
    return new;
  end if;

  select rol into actor_role
  from public.profiles
  where id = auth.uid();

  if actor_role = 'super_admin' then
    return new;
  end if;

  if actor_role = 'admin'
     and old.rol <> 'super_admin'
     and new.rol in ('cliente', 'operador', 'admin') then
    return new;
  end if;

  raise exception 'No tenés permisos para cambiar este rol.';
end;
$$;

drop trigger if exists protect_profile_role_changes on public.profiles;
create trigger protect_profile_role_changes
before update of rol on public.profiles
for each row execute function public.protect_profile_role_changes();

alter table public.audit_logs enable row level security;

drop policy if exists "Super admins can read audit logs" on public.audit_logs;
create policy "Super admins can read audit logs"
on public.audit_logs
for select
to authenticated
using (public.current_user_role() = 'super_admin');

drop policy if exists "Internal users can read all profiles" on public.profiles;
create policy "Internal users can read all profiles"
on public.profiles
for select
to authenticated
using (public.is_current_user_internal());
