import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import test from "node:test"
import { PGlite } from "@electric-sql/pglite"

// RPC internas SECURITY DEFINER: el navegador (anon/authenticated) no las
// puede ejecutar; el servidor (service_role) y los triggers (owner) sí.

const source = (path: string) => readFileSync(new URL(path, import.meta.url), "utf8")
const MIGRATION = source("../../supabase/migrations/20261001110000_revoke_public_internal_rpcs.sql")

async function setup() {
  const db = new PGlite()
  await db.exec(`
    create role anon; create role authenticated; create role service_role;
    create table productos(id bigint generated by default as identity primary key, nombre text);
    -- Grants por defecto de Supabase: toda función nueva queda ejecutable por anon/authenticated.
    create function public.ensure_cost_catalog_product(p_name text, p_sku text) returns bigint
      language sql security definer set search_path = public as $$ insert into productos(nombre) values (p_name) returning id $$;
    create function public.email_exists_for_password_recovery(p_email text) returns boolean
      language sql security definer set search_path = public as $$ select false $$;
    grant execute on function public.ensure_cost_catalog_product(text, text) to anon, authenticated, service_role;
    grant execute on function public.email_exists_for_password_recovery(text) to anon, authenticated, service_role;
    grant usage on schema public to anon, authenticated, service_role;
  `)
  return db
}

const canExecute = async (db: PGlite, role: string, signature: string) =>
  (await db.query<{ ok: boolean }>("select has_function_privilege($1, $2, 'execute') ok", [role, signature])).rows[0].ok

test("anon/authenticated ya no ejecutan ensure_cost_catalog_product ni email_exists_for_password_recovery; service_role sí", async () => {
  const db = await setup()
  try {
    await db.exec(MIGRATION)
    await db.exec(MIGRATION)
    for (const signature of ["public.ensure_cost_catalog_product(text, text)", "public.email_exists_for_password_recovery(text)"]) {
      for (const role of ["anon", "authenticated", "public"]) {
        assert.equal(await canExecute(db, role, signature), false, `${role} no ejecuta ${signature}`)
      }
      assert.equal(await canExecute(db, "service_role", signature), true, `service_role conserva ${signature}`)
    }
    await db.exec("set role anon")
    await assert.rejects(db.query("select public.ensure_cost_catalog_product('Producto intruso', null)"), /permission denied/)
    await db.exec("reset role")
    assert.equal(Number((await db.query<{ n: number }>("select count(*)::int n from productos")).rows[0].n), 0, "no se creó ningún producto")
  } finally {
    await db.close()
  }
})

test("la migración no falla si alguna función no existe (entornos parciales)", async () => {
  const db = new PGlite()
  try {
    await db.exec("create role anon; create role authenticated; create role service_role;")
    await db.exec(MIGRATION)
  } finally {
    await db.close()
  }
})

test("la app sólo usa ensure_cost_catalog_product con el cliente service_role", () => {
  const route = source("../../app/api/admin/costs/new-article/route.ts")
  assert.match(route, /auth\.admin\.rpc\("ensure_cost_catalog_product"/)
})
