import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import test from "node:test"
import { PGlite } from "@electric-sql/pglite"

// Migración de reseñas sobre PostgreSQL (PGlite) con el esquema, las policies
// y los grants de producción (baseline 2026-09-21): plazo de 15 días desde
// delivered_at, comentario obligatorio, destacado solo por service_role (API
// Admin) y compatibilidad con reseñas existentes.

const readMigration = (name: string) =>
  readFileSync(new URL(`../../supabase/migrations/${name}`, import.meta.url), "utf8")

const FEATURED_MIGRATION = readMigration("20261001150000_reviews_featured_and_review_window.sql")
const PRIVACY_MIGRATION = readMigration("20261001160000_reviews_private_columns_and_experience_featured.sql")
// Esquema vigente: ambas migraciones en el orden en que se aplican.
const MIGRATION = `${FEATURED_MIGRATION}\n${PRIVACY_MIGRATION}`

const CLIENT = "00000000-0000-0000-0000-00000000000a"
const OTHER = "00000000-0000-0000-0000-00000000000b"

async function setup() {
  const db = new PGlite()
  await db.exec(`
    create role anon; create role authenticated; create role service_role bypassrls;
    create schema auth;
    create table auth.users (id uuid primary key);
    create function auth.uid() returns uuid language sql stable as
      $$ select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
    grant usage on schema auth, public to anon, authenticated, service_role;
    grant execute on function auth.uid() to anon, authenticated, service_role;
    insert into auth.users values ('${CLIENT}'), ('${OTHER}');

    create table public.productos (id bigint primary key);
    insert into public.productos values (1);
    create table public.ordenes (
      id bigint primary key, usuario_id uuid, estado text not null,
      payment_status text, delivered_at timestamptz
    );
    grant select on public.ordenes to anon, authenticated, service_role;

    create table public.reviews (
      id bigint generated by default as identity primary key,
      user_id uuid not null references auth.users(id) on delete cascade,
      order_id bigint not null references public.ordenes(id) on delete cascade,
      rating smallint not null check (rating between 1 and 5),
      comment text not null check (char_length(trim(comment)) between 0 and 150),
      nickname text not null, city text not null, province text not null,
      approved boolean not null default true,
      created_at timestamptz not null default now(),
      product_id bigint references public.productos(id) on delete set null
    );
    create unique index reviews_one_per_order_product_idx on public.reviews (user_id, order_id, product_id) nulls not distinct;
    alter table public.reviews enable row level security;
    create policy "Customers can create reviews for paid orders" on public.reviews for insert to authenticated
      with check (auth.uid() = user_id and exists (select 1 from public.ordenes
        where ordenes.id = reviews.order_id and ordenes.usuario_id = auth.uid()
          and (ordenes.estado = any (array['pagado','enviado','entregado']) or ordenes.payment_status = 'approved')));
    create policy "Customers can delete their own reviews" on public.reviews for delete to authenticated using (auth.uid() = user_id);
    create policy "Public can read approved reviews" on public.reviews for select using (approved = true);
    grant all on public.reviews to anon, authenticated, service_role;

    insert into public.ordenes values
      (1, '${CLIENT}', 'entregado', 'approved', now() - interval '3 days'),
      (2, '${CLIENT}', 'entregado', 'approved', now() - interval '14 days 23 hours'),
      (3, '${CLIENT}', 'entregado', 'approved', now() - interval '15 days 1 second'),
      (4, '${CLIENT}', 'pagado', 'approved', null),
      (5, '${CLIENT}', 'cancelado', 'approved', now() - interval '2 days'),
      (6, '${OTHER}', 'entregado', 'approved', now() - interval '2 days'),
      (7, '${CLIENT}', 'entregado', 'approved', now() - interval '90 days'),
      (8, '${CLIENT}', 'enviado', 'approved', now() + interval '1 day');

    -- Reseñas existentes antes de la migración: comentario vacío (permitido
    -- por la regla anterior) y compra entregada hace 90 días.
    insert into public.reviews (user_id, order_id, product_id, rating, comment, nickname, city, province)
    values ('${CLIENT}', 7, null, 5, '', 'Lucas', 'Rosario', 'Santa Fe'),
           ('${CLIENT}', 7, 1, 4, 'Muy buen producto, llegó perfecto', 'Lucas', 'Rosario', 'Santa Fe');
  `)
  return db
}

const insertAs = (db: PGlite, orderId: number, comment: string, extra = "") =>
  db.query<{ id: number; featured: boolean; featured_at: string | null }>(
    `insert into public.reviews (user_id, order_id, product_id, rating, comment, nickname, city, province${extra ? ", featured" : ""})
     values ($1, $2, null, 5, $3, 'Lucas', 'Rosario', 'Santa Fe'${extra ? `, ${extra}` : ""}) returning id, featured, featured_at`,
    [CLIENT, orderId, comment],
  )

async function asRole<T>(db: PGlite, role: string, run: () => Promise<T>) {
  await db.exec(`set role ${role}; set request.jwt.claim.sub = '${CLIENT}'`)
  try {
    return await run()
  } finally {
    await db.exec("reset role; reset request.jwt.claim.sub")
  }
}

test("migración idempotente y reseñas existentes intactas (O)", async () => {
  const db = await setup()
  try {
    await db.exec(MIGRATION)
    await db.exec(MIGRATION)
    const rows = (await db.query<{ comment: string; featured: boolean; approved: boolean }>(
      "select comment, featured, approved from public.reviews order by id",
    )).rows
    assert.deepEqual(rows, [
      { comment: "", featured: false, approved: true },
      { comment: "Muy buen producto, llegó perfecto", featured: false, approved: true },
    ])
    // Un UPDATE ajeno a `featured` sobre una reseña vieja (sin comentario y
    // fuera de plazo) no se revalida: las reglas nuevas aplican solo a INSERT.
    await asRole(db, "service_role", () => db.query("update public.reviews set nickname = 'Lucas R' where id = 1"))
    // Borrar un producto pone product_id en null (UPDATE vía FK) sin bloquearse.
    await db.exec("delete from public.reviews where id = 1; delete from public.productos where id = 1")
    assert.equal((await db.query<{ product_id: number | null }>("select product_id from public.reviews where id = 2")).rows[0].product_id, null)
    // Lectura pública (anon) sigue funcionando.
    const anon = await asRole(db, "anon", () => db.query("select id from public.reviews"))
    assert.equal(anon.rows.length, 1)
  } finally {
    await db.close()
  }
})

test("D/E. plazo de 15 días desde delivered_at, validado en la base", async () => {
  const db = await setup()
  try {
    await db.exec(MIGRATION)
    await asRole(db, "service_role", async () => {
      assert.equal((await insertAs(db, 1, "Excelente producto")).rows.length, 1)
      assert.equal((await insertAs(db, 2, "Llegó justo a tiempo")).rows.length, 1, "día 15: permitido")
      await assert.rejects(insertAs(db, 3, "Excelente producto"), /REVIEW_WINDOW_EXPIRED/, "día 16: rechazado")
      await assert.rejects(insertAs(db, 7, "Excelente producto"), /REVIEW_WINDOW_EXPIRED/)
      await assert.rejects(insertAs(db, 4, "Excelente producto"), /REVIEW_NOT_DELIVERED/, "sin delivered_at")
      await assert.rejects(insertAs(db, 5, "Excelente producto"), /REVIEW_NOT_DELIVERED/, "cancelado")
      await assert.rejects(insertAs(db, 8, "Excelente producto"), /REVIEW_NOT_DELIVERED/, "entrega futura")
      await assert.rejects(insertAs(db, 6, "Excelente producto"), /REVIEW_ORDER_INVALID/, "pedido de otro usuario")
    })
  } finally {
    await db.close()
  }
})

test("F/G. comentario vacío, con espacios o demasiado corto se rechaza en la base", async () => {
  const db = await setup()
  try {
    await db.exec(MIGRATION)
    await asRole(db, "service_role", async () => {
      for (const comment of ["", "        ", "bien", " o k "]) {
        await assert.rejects(insertAs(db, 1, comment), /REVIEW_COMMENT_TOO_SHORT/, JSON.stringify(comment))
      }
    })
  } finally {
    await db.close()
  }
})

test("L. el cliente no puede insertar, actualizar ni autodestacarse", async () => {
  const db = await setup()
  try {
    await db.exec(MIGRATION)
    const policies = (await db.query("select policyname from pg_policies where tablename = 'reviews' and cmd = 'INSERT'")).rows
    assert.deepEqual(policies, [])

    await asRole(db, "authenticated", async () => {
      await assert.rejects(insertAs(db, 1, "Excelente producto", "true"), /permission denied/)
      await assert.rejects(db.query("update public.reviews set featured = true where id = 1"), /permission denied/)
    })
    await asRole(db, "anon", async () => {
      await assert.rejects(db.query("update public.reviews set featured = true"), /permission denied/)
    })

    // Aunque alguien volviera a otorgar UPDATE, el trigger lo sigue impidiendo.
    await db.exec(`grant update on public.reviews to authenticated;
      create policy tmp_update on public.reviews for update to authenticated using (true) with check (true)`)
    await asRole(db, "authenticated", async () => {
      await assert.rejects(db.query("update public.reviews set featured = true where id = 2"), /REVIEW_FEATURED_FORBIDDEN/)
    })

    // Una reseña nueva nunca nace destacada, aunque el insert lo pida.
    const created = await asRole(db, "service_role", () => insertAs(db, 1, "Excelente producto", "true"))
    assert.deepEqual(created.rows[0], { id: created.rows[0].id, featured: false, featured_at: null })
  } finally {
    await db.close()
  }
})

test("M/N. service_role (API Admin) destaca y quita; Home lee solo destacadas", async () => {
  const db = await setup()
  try {
    await db.exec(MIGRATION)
    await asRole(db, "service_role", async () => {
      const first = (await insertAs(db, 1, "Excelente producto")).rows[0].id
      const second = (await insertAs(db, 2, "Todo bien, llegó rápido")).rows[0].id

      const featured = await db.query<{ featured: boolean; featured_at: string | null }>(
        "update public.reviews set featured = true where id = $1 returning featured, featured_at", [second],
      )
      assert.equal(featured.rows[0].featured, true)
      assert.ok(featured.rows[0].featured_at, "featured_at registrado")

      await assert.rejects(
        db.query("update public.reviews set featured = true where id = 1"),
        /REVIEW_FEATURED_REQUIRES_COMMENT/,
        "reseña existente sin comentario no se destaca",
      )

      // F. Reseña de PRODUCTO: la base rechaza destacarla aunque venga de
      // service_role (API Admin); el Home tampoco la mostraría.
      const productReview = (await db.query<{ id: number }>(
        `insert into public.reviews (user_id, order_id, product_id, rating, comment, nickname, city, province)
         values ($1, 1, 1, 5, 'Muy buen producto, llegó perfecto', 'Lucas', 'Rosario', 'Santa Fe') returning id`,
        [CLIENT],
      )).rows[0].id
      await assert.rejects(
        db.query("update public.reviews set featured = true where id = $1", [productReview]),
        /REVIEW_FEATURED_EXPERIENCE_ONLY/,
      )

      const home = await db.query<{ id: number }>(
        "select id from public.reviews where approved and featured and product_id is null order by created_at desc, id desc",
      )
      assert.deepEqual(home.rows.map((row) => row.id), [second], "sólo la experiencia destacada")
      assert.ok(!home.rows.some((row) => row.id === first), "experiencia NO destacada: no aparece")
      assert.ok(!home.rows.some((row) => row.id === productReview), "reseña de producto destacada: no aparece")

      const removed = await db.query<{ featured: boolean; featured_at: string | null }>(
        "update public.reviews set featured = false where id = $1 returning featured, featured_at", [second],
      )
      assert.deepEqual(removed.rows[0], { featured: false, featured_at: null })
    })
  } finally {
    await db.close()
  }
})

// ─────────── 20261001160000: privacidad de la lectura directa ───────────

const SENSITIVE_COLUMNS = ["user_id", "order_id", "nickname", "comment", "city", "province", "featured", "created_at"]

test("A. anon no lee user_id/order_id ni ninguna columna fuera de las públicas; sí el promedio del catálogo", async () => {
  const db = await setup()
  try {
    await db.exec(MIGRATION)
    await db.exec(MIGRATION)
    await asRole(db, "anon", async () => {
      for (const column of SENSITIVE_COLUMNS) {
        await assert.rejects(db.query(`select ${column} from public.reviews`), /permission denied/, column)
      }
      await assert.rejects(db.query("select * from public.reviews"), /permission denied/)
      await assert.rejects(
        db.query("select count(*) from public.reviews where user_id is not null"),
        /permission denied/,
        "tampoco como filtro",
      )
      // Lo único que lee el navegador directo: product-review-summary.ts.
      const summary = await db.query<{ product_id: number; rating: number }>(
        "select product_id, rating from public.reviews where approved = true and product_id in (1)",
      )
      assert.deepEqual(summary.rows, [{ product_id: 1, rating: 4 }])
      await assert.rejects(db.query("delete from public.reviews"), /permission denied/, "anon no borra")
      await assert.rejects(db.query("truncate public.reviews"), /permission denied/, "anon no trunca")
    })
  } finally {
    await db.close()
  }
})

test("B. authenticated tampoco extrae columnas sensibles; sólo borra su propia reseña; service_role conserva todo", async () => {
  const db = await setup()
  try {
    await db.exec(MIGRATION)
    const others = await asRole(db, "service_role", () => db.query<{ id: number }>(
      `insert into public.reviews (user_id, order_id, product_id, rating, comment, nickname, city, province)
       values ($1, 6, null, 5, 'Excelente atención de BEYONIX', 'Otro', 'Rosario', 'Santa Fe') returning id`,
      [OTHER],
    ))
    const otherId = others.rows[0].id

    await asRole(db, "authenticated", async () => {
      for (const column of SENSITIVE_COLUMNS) {
        await assert.rejects(db.query(`select ${column} from public.reviews`), /permission denied/, column)
      }
      await assert.rejects(db.query("select * from public.reviews"), /permission denied/)
      await assert.rejects(db.query("truncate public.reviews"), /permission denied/)

      const foreign = await db.query("delete from public.reviews where id = $1 returning id", [otherId])
      assert.equal(foreign.rows.length, 0, "no borra reseñas ajenas")
      const own = await db.query<{ id: number }>("delete from public.reviews where id = 2 returning id")
      assert.deepEqual(own.rows, [{ id: 2 }], "borra su propia reseña (policy existente)")
    })

    const full = await asRole(db, "service_role", () =>
      db.query<{ user_id: string }>("select user_id, order_id, nickname from public.reviews where id = $1", [otherId]),
    )
    assert.equal(full.rows[0].user_id, OTHER, "las APIs del servidor siguen leyendo todo")
  } finally {
    await db.close()
  }
})

test("D/F/G. se destaca una experiencia; nunca una reseña de producto (tampoco con service_role); quitar sí", async () => {
  const db = await setup()
  try {
    // Estado previo: con la primera migración una reseña de producto podía
    // quedar destacada. Tras la nueva se puede quitar, pero no volver a poner.
    await db.exec(FEATURED_MIGRATION)
    await asRole(db, "service_role", () => db.query("update public.reviews set featured = true where id = 2"))
    await db.exec(PRIVACY_MIGRATION)

    await asRole(db, "service_role", async () => {
      const experience = (await insertAs(db, 1, "Excelente atención, llegó rápido")).rows[0].id
      const featured = await db.query<{ featured: boolean }>(
        "update public.reviews set featured = true where id = $1 returning featured",
        [experience],
      )
      assert.equal(featured.rows[0].featured, true, "D. experiencia general destacable")

      const removed = await db.query<{ featured: boolean }>(
        "update public.reviews set featured = false where id = 2 returning featured",
      )
      assert.equal(removed.rows[0].featured, false, "una reseña de producto destacada de antes se puede quitar")
      await assert.rejects(
        db.query("update public.reviews set featured = true where id = 2"),
        /REVIEW_FEATURED_EXPERIENCE_ONLY/,
        "F. reseña de producto: rechazada por la base",
      )

      const home = await db.query<{ id: number }>(
        "select id from public.reviews where approved and featured and product_id is null order by created_at desc, id desc",
      )
      assert.deepEqual(home.rows.map((row) => row.id), [experience], "G. Home: sólo experiencias destacadas")
    })
  } finally {
    await db.close()
  }
})
