-- Reclamos con cambio de producto: logística Andreani de ida y vuelta.
--
-- QUÉ AGREGA (sin rehacer reclamos, recepción ni reemplazos):
-- 1. Mensajes automáticos idempotentes: order_claim_messages.system_key única
--    por reclamo. Reintentos, consultas repetidas o re-guardados no duplican.
-- 2. order_claim_shipments: UN envío por reclamo y por tramo:
--      devolucion -> cliente -> BEYONIX (contrato de DEVOLUCIONES; modalidad
--                    retiro_domicilio o despacho_sucursal). Se crea
--                    "pendiente" al aceptar el cambio.
--      reemplazo  -> BEYONIX -> cliente (contratos de VENTA; modalidad
--                    entrega_domicilio o entrega_sucursal). Sólo cuando el
--                    reemplazo ya está registrado para todas las unidades
--                    reclamadas (create_order_replacement: recepción + salida
--                    de stock, exactamente una vez).
--    Estados: pendiente -> generada -> en_transito -> entregada, más
--    incidencia (puede seguir avanzando). "entregada" es terminal.
-- 3. Creación idempotente (mismo criterio que el envío B2C del pedido): el
--    tramo se toma con un token ANTES de llamar a Andreani; resultado
--    desconocido (timeout/5xx) -> revisión manual; nunca un segundo POST
--    automático. Sólo un admin concilia (existe / no existe) con nota.
-- 4. Efectos de cada tramo en la misma transacción:
--      devolución entregada -> mensaje al cliente + aviso al Admin para
--                              registrar la recepción física (sin tocar stock);
--      reemplazo generado   -> "Tu producto de reemplazo ya fue despachado." +
--                              seguimiento/modalidad; completa los datos del
--                              envío del reemplazo en el reclamo;
--      reemplazo entregado  -> "Andreani informó que tu producto de reemplazo
--                              fue entregado." + aviso al Admin para cerrar.
--    Ninguna función de este archivo modifica stock.
-- 5. Costo: sólo si Andreani lo informa; nunca se cobra al cliente.
-- Todo es service_role; el cliente lee sólo campos seguros vía la API.

begin;

-- 1. Mensajes automáticos idempotentes -----------------------------------

alter table public.order_claim_messages
  add column if not exists system_key text;

comment on column public.order_claim_messages.system_key is
  'Clave de mensajes automáticos (p. ej. change_accepted). Única por reclamo: evita duplicados en reintentos.';

create unique index if not exists order_claim_messages_system_key_unique
  on public.order_claim_messages (claim_id, system_key)
  where system_key is not null;

-- 2. Envíos Andreani del reclamo ------------------------------------------

create table if not exists public.order_claim_shipments (
  id bigint generated by default as identity primary key,
  claim_id bigint not null references public.order_claims(id) on delete restrict,
  order_id bigint not null references public.ordenes(id) on delete restrict,
  direction text not null check (direction in ('devolucion', 'reemplazo')),
  status text not null default 'pendiente'
    check (status in ('pendiente', 'generada', 'en_transito', 'entregada', 'incidencia')),
  modality text,
  environment text check (environment in ('QA', 'PROD')),
  contract text,
  andreani_envio_id text,
  andreani_tracking text,
  andreani_estado text,
  andreani_last_event text,
  andreani_last_event_at timestamptz,
  cost_amount numeric(12, 2) check (cost_amount is null or cost_amount >= 0),
  creation_status text not null default 'not_started'
    check (creation_status in ('not_started', 'processing', 'created', 'failed', 'manual_review')),
  creation_token uuid,
  creation_started_at timestamptz,
  creation_error text,
  delivered_at timestamptz,
  last_checked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint order_claim_shipments_one_per_direction unique (claim_id, direction),
  constraint order_claim_shipments_modality check (
    modality is null
    or (direction = 'devolucion' and modality in ('retiro_domicilio', 'despacho_sucursal'))
    or (direction = 'reemplazo' and modality in ('entrega_domicilio', 'entrega_sucursal'))
  ),
  constraint order_claim_shipments_created_complete check (
    creation_status <> 'created'
    or (andreani_envio_id is not null and modality is not null and environment is not null and contract is not null)
  ),
  constraint order_claim_shipments_status_requires_creation check (
    status = 'pendiente' or creation_status = 'created'
  ),
  constraint order_claim_shipments_delivered_at check ((status = 'entregada') = (delivered_at is not null))
);

comment on table public.order_claim_shipments is
  'Envíos Andreani de un reclamo con cambio de producto: devolución (cliente -> BEYONIX) y reemplazo (BEYONIX -> cliente). No modifica stock.';
comment on column public.order_claim_shipments.cost_amount is
  'Costo sólo si Andreani lo informa. Nunca se cobra al cliente: Andreani lo factura a BEYONIX según contrato.';

create unique index if not exists order_claim_shipments_andreani_envio_unique
  on public.order_claim_shipments (environment, andreani_envio_id)
  where andreani_envio_id is not null;
create index if not exists order_claim_shipments_tracking_queue_idx
  on public.order_claim_shipments (last_checked_at nulls first, id)
  where creation_status = 'created' and status in ('generada', 'en_transito', 'incidencia');

alter table public.order_claim_shipments enable row level security;
revoke all on table public.order_claim_shipments from public, anon, authenticated;
grant select, insert, update on table public.order_claim_shipments to service_role;

-- Tramo listo para generar/conciliar: cambio aceptado y, para el reemplazo,
-- todas las unidades reclamadas ya registradas como reemplazo.
create or replace function public.order_claim_shipment_ready(p_claim_id bigint, p_direction text)
returns boolean
language sql
stable
set search_path = public
as $$
  select exists (
    select 1 from public.order_claims c
    where c.id = p_claim_id
      and c.resolution = 'cambio_producto'
      and c.status in ('aprobado', 'cambio_pendiente')
      and (
        p_direction = 'devolucion'
        or (
          p_direction = 'reemplazo'
          and coalesce((select sum((item->>'quantity')::integer) from jsonb_array_elements(c.affected_items) item), 0) > 0
          and coalesce((select sum(r.quantity) from public.order_replacements r where r.claim_id = c.id), 0)
              >= coalesce((select sum((item->>'quantity')::integer) from jsonb_array_elements(c.affected_items) item), 0)
        )
      )
  )
$$;

revoke all on function public.order_claim_shipment_ready(bigint, text) from public, anon, authenticated;
grant execute on function public.order_claim_shipment_ready(bigint, text) to service_role;

-- 3. Aceptación del cambio: mensajes + devolución pendiente ---------------

create or replace function public.order_claim_change_accepted()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_now timestamptz := now();
begin
  if new.resolution is distinct from 'cambio_producto'
     or new.status not in ('aprobado', 'cambio_pendiente')
     or coalesce(new.failure_type, '') in ('consulta_pedido', 'cancelar_compra') then
    return new;
  end if;
  -- Sólo la TRANSICIÓN a "cambio aceptado".
  if tg_op = 'UPDATE' and old.resolution is not distinct from 'cambio_producto'
     and old.status in ('aprobado', 'cambio_pendiente') then
    return new;
  end if;

  -- Un instante antes de la transacción: quedan en orden y antes de un texto
  -- libre del admin guardado en la misma operación.
  insert into public.order_claim_messages (claim_id, author_user_id, author_role, message, system_key, created_at)
  values
    (new.id, null, 'admin', 'BEYONIX aceptó el cambio del producto.', 'change_accepted',
     v_now - interval '2 milliseconds'),
    (new.id, null, 'admin',
     'Para continuar, te pedimos que prepares el producto completo, incluyendo caja, bolsas, manuales, accesorios y todos los elementos recibidos, correctamente embalado y en el mejor estado posible. Esto nos permitirá revisar el producto y agilizar el reemplazo.',
     'change_packing_instructions', v_now - interval '1 millisecond')
  on conflict (claim_id, system_key) where system_key is not null do nothing;

  insert into public.order_claim_shipments (claim_id, order_id, direction)
  values (new.id, new.order_id, 'devolucion')
  on conflict (claim_id, direction) do nothing;

  return new;
end;
$$;

revoke all on function public.order_claim_change_accepted() from public, anon, authenticated;

drop trigger if exists zz_order_claim_change_accepted on public.order_claims;
create trigger zz_order_claim_change_accepted
  after insert or update of status, resolution on public.order_claims
  for each row execute function public.order_claim_change_accepted();

-- 4. Efectos de un tramo generado (creación o conciliación) ----------------

create or replace function public.order_claim_shipment_created_effects(p_shipment public.order_claim_shipments)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_details text;
begin
  insert into public.order_audit_events (order_id, actor_type, action, previous_status, new_status, metadata)
  values (p_shipment.order_id, 'system', 'claim_shipment_created', 'pendiente', 'generada',
    jsonb_build_object('claimId', p_shipment.claim_id, 'direction', p_shipment.direction,
      'envioId', p_shipment.andreani_envio_id, 'tracking', p_shipment.andreani_tracking,
      'modality', p_shipment.modality, 'environment', p_shipment.environment,
      'costAmount', p_shipment.cost_amount));

  if p_shipment.direction <> 'reemplazo' then return; end if;

  v_details := concat_ws(E'\n',
    'Seguimiento Andreani: ' || coalesce(p_shipment.andreani_tracking, p_shipment.andreani_envio_id),
    case p_shipment.modality
      when 'entrega_sucursal' then 'Modalidad: retiro en la sucursal Andreani que elegiste en tu compra. Andreani te avisa cuando esté disponible; llevá tu DNI.'
      else 'Modalidad: entrega en el domicilio de tu compra. Si no hay nadie, Andreani deja un aviso para coordinar.'
    end);
  insert into public.order_claim_messages (claim_id, author_user_id, author_role, message, system_key, created_at)
  values
    (p_shipment.claim_id, null, 'admin', 'Tu producto de reemplazo ya fue despachado.', 'replacement_dispatched',
     clock_timestamp()),
    (p_shipment.claim_id, null, 'admin', v_details, 'replacement_dispatch_details',
     clock_timestamp() + interval '1 millisecond')
  on conflict (claim_id, system_key) where system_key is not null do nothing;

  -- Mismos datos que antes se cargaban a mano en el reclamo.
  update public.order_claims
  set replacement_shipping_company = coalesce(replacement_shipping_company, 'Andreani'),
      replacement_tracking = coalesce(replacement_tracking, p_shipment.andreani_tracking, p_shipment.andreani_envio_id),
      replacement_sent_at = coalesce(replacement_sent_at, now())
  where id = p_shipment.claim_id;
end;
$$;

revoke all on function public.order_claim_shipment_created_effects(public.order_claim_shipments) from public, anon, authenticated;

-- 5. Creación idempotente de la operación Andreani ------------------------

-- Toma el tramo. Devuelve la fila 'processing' con el token del llamador, la
-- fila ya creada (el llamador la reutiliza) o NULL si otra creación está en
-- curso o requiere revisión manual.
create or replace function public.claim_order_claim_shipment_creation(
  p_claim_id bigint,
  p_direction text,
  p_token uuid,
  p_environment text,
  p_modality text,
  p_contract text
)
returns public.order_claim_shipments
language plpgsql
security definer
set search_path = public
as $$
declare
  v_shipment public.order_claim_shipments%rowtype;
  v_order_id bigint;
begin
  if auth.role() is distinct from 'service_role' then raise exception 'FORBIDDEN' using errcode = '42501'; end if;
  if p_token is null or p_direction not in ('devolucion', 'reemplazo') or p_environment not in ('QA', 'PROD')
     or coalesce(btrim(p_contract), '') = '' or p_modality is null then
    raise exception 'CLAIM_SHIPMENT_INVALID';
  end if;

  select order_id into v_order_id from public.order_claims where id = p_claim_id for update;
  if not found then raise exception 'CLAIM_NOT_FOUND'; end if;
  insert into public.order_claim_shipments (claim_id, order_id, direction)
  values (p_claim_id, v_order_id, p_direction)
  on conflict (claim_id, direction) do nothing;
  select * into v_shipment from public.order_claim_shipments
  where claim_id = p_claim_id and direction = p_direction for update;

  if v_shipment.creation_status = 'created' then return v_shipment; end if;
  if v_shipment.creation_status in ('processing', 'manual_review') then return null; end if;
  if not public.order_claim_shipment_ready(p_claim_id, p_direction) then
    raise exception 'CLAIM_SHIPMENT_NOT_READY';
  end if;

  update public.order_claim_shipments
  set creation_status = 'processing',
      creation_token = p_token,
      creation_started_at = clock_timestamp(),
      creation_error = null,
      environment = p_environment,
      modality = p_modality,
      contract = btrim(p_contract),
      updated_at = clock_timestamp()
  where id = v_shipment.id
  returning * into v_shipment;

  insert into public.order_audit_events (order_id, actor_type, action, previous_status, new_status, metadata)
  values (v_shipment.order_id, 'system', 'claim_shipment_creation_started', null, 'processing',
    jsonb_build_object('claimId', p_claim_id, 'direction', p_direction, 'environment', p_environment,
      'modality', p_modality));
  return v_shipment;
end;
$$;

-- Guarda la operación creada. Idempotente con el mismo envío; nunca pisa otro.
create or replace function public.complete_order_claim_shipment_creation(
  p_claim_id bigint,
  p_direction text,
  p_token uuid,
  p_envio_id text,
  p_tracking text,
  p_estado text,
  p_cost_amount numeric
)
returns public.order_claim_shipments
language plpgsql
security definer
set search_path = public
as $$
declare
  v_shipment public.order_claim_shipments%rowtype;
begin
  if auth.role() is distinct from 'service_role' then raise exception 'FORBIDDEN' using errcode = '42501'; end if;
  if coalesce(btrim(p_envio_id), '') = '' or (p_cost_amount is not null and p_cost_amount < 0) then
    raise exception 'CLAIM_SHIPMENT_INVALID';
  end if;

  select * into v_shipment from public.order_claim_shipments
  where claim_id = p_claim_id and direction = p_direction for update;
  if not found then raise exception 'CLAIM_SHIPMENT_NOT_FOUND'; end if;
  if v_shipment.creation_status = 'created' then
    if v_shipment.andreani_envio_id = btrim(p_envio_id) then return v_shipment; end if;
    raise exception 'CLAIM_SHIPMENT_ALREADY_CREATED';
  end if;
  if v_shipment.creation_status is distinct from 'processing' or v_shipment.creation_token is distinct from p_token then
    raise exception 'CLAIM_SHIPMENT_NOT_CLAIMED';
  end if;

  update public.order_claim_shipments
  set creation_status = 'created',
      status = 'generada',
      creation_token = null,
      creation_error = null,
      andreani_envio_id = btrim(p_envio_id),
      andreani_tracking = nullif(btrim(coalesce(p_tracking, '')), ''),
      andreani_estado = nullif(btrim(coalesce(p_estado, '')), ''),
      cost_amount = p_cost_amount,
      updated_at = clock_timestamp()
  where id = v_shipment.id
  returning * into v_shipment;

  perform public.order_claim_shipment_created_effects(v_shipment);
  return v_shipment;
end;
$$;

-- Registra un intento fallido o una creación bloqueada.
--   blocked       -> configuración/validación ANTES de llamar a Andreani
--                    (sin token; no cambia el estado de creación).
--   failed        -> Andreani rechazó explícitamente: se puede reintentar.
--   manual_review -> resultado desconocido (timeout/5xx/respuesta inválida):
--                    Andreani pudo haber creado la operación; no se reintenta.
create or replace function public.fail_order_claim_shipment_creation(
  p_claim_id bigint,
  p_direction text,
  p_token uuid,
  p_error text,
  p_outcome text
)
returns public.order_claim_shipments
language plpgsql
security definer
set search_path = public
as $$
declare
  v_shipment public.order_claim_shipments%rowtype;
  v_order_id bigint;
  v_message text := left(coalesce(nullif(btrim(p_error), ''), 'No se pudo generar el envío Andreani.'), 500);
begin
  if auth.role() is distinct from 'service_role' then raise exception 'FORBIDDEN' using errcode = '42501'; end if;
  if p_outcome not in ('blocked', 'failed', 'manual_review') or p_direction not in ('devolucion', 'reemplazo') then
    raise exception 'CLAIM_SHIPMENT_INVALID';
  end if;

  if p_outcome = 'blocked' then
    -- Sólo sobre un cambio aceptado: el motivo queda visible para Admin.
    select order_id into v_order_id from public.order_claims
    where id = p_claim_id and resolution = 'cambio_producto' and status in ('aprobado', 'cambio_pendiente');
    if not found then return null; end if;
    insert into public.order_claim_shipments (claim_id, order_id, direction)
    values (p_claim_id, v_order_id, p_direction)
    on conflict (claim_id, direction) do nothing;
  end if;

  select * into v_shipment from public.order_claim_shipments
  where claim_id = p_claim_id and direction = p_direction for update;
  if not found then raise exception 'CLAIM_SHIPMENT_NOT_FOUND'; end if;

  if p_outcome = 'blocked' then
    if v_shipment.creation_status not in ('not_started', 'failed') then return v_shipment; end if;
    update public.order_claim_shipments
    set creation_error = v_message, updated_at = clock_timestamp()
    where id = v_shipment.id returning * into v_shipment;
    return v_shipment;
  end if;

  if v_shipment.creation_status is distinct from 'processing' or v_shipment.creation_token is distinct from p_token then
    return v_shipment;
  end if;
  update public.order_claim_shipments
  set creation_status = p_outcome,
      creation_token = null,
      creation_error = v_message,
      updated_at = clock_timestamp()
  where id = v_shipment.id
  returning * into v_shipment;

  insert into public.order_audit_events (order_id, actor_type, action, previous_status, new_status, metadata)
  values (v_shipment.order_id, 'system', 'claim_shipment_creation_failed', 'processing', p_outcome,
    jsonb_build_object('claimId', p_claim_id, 'direction', p_direction, 'error', v_message));
  return v_shipment;
end;
$$;

-- Conciliación manual (sólo admin/super_admin, con nota): después de un
-- resultado incierto, el admin confirma por fuera si Andreani creó o no la
-- operación. Nunca reintenta el POST.
create or replace function public.resolve_order_claim_shipment_reconciliation(
  p_claim_id bigint,
  p_direction text,
  p_actor_id uuid,
  p_resolution text,
  p_envio_id text,
  p_tracking text,
  p_notes text
)
returns public.order_claim_shipments
language plpgsql
security definer
set search_path = public
as $$
declare
  v_shipment public.order_claim_shipments%rowtype;
  v_role text;
begin
  if auth.role() is distinct from 'service_role' then raise exception 'FORBIDDEN' using errcode = '42501'; end if;
  select rol into v_role from public.profiles where id = p_actor_id;
  if coalesce(v_role, '') not in ('admin', 'super_admin') then raise exception 'CLAIM_SHIPMENT_RECONCILIATION_FORBIDDEN'; end if;
  if p_resolution not in ('created', 'not_created') or length(btrim(coalesce(p_notes, ''))) < 5
     or (p_resolution = 'created' and coalesce(btrim(p_envio_id), '') = '') then
    raise exception 'CLAIM_SHIPMENT_INVALID';
  end if;

  select * into v_shipment from public.order_claim_shipments
  where claim_id = p_claim_id and direction = p_direction for update;
  if not found then raise exception 'CLAIM_SHIPMENT_NOT_FOUND'; end if;
  -- Sólo un resultado incierto, o una toma colgada (el proceso murió).
  if not (v_shipment.creation_status = 'manual_review'
          or (v_shipment.creation_status = 'processing' and v_shipment.creation_started_at < clock_timestamp() - interval '10 minutes')) then
    raise exception 'CLAIM_SHIPMENT_RECONCILIATION_NOT_PENDING';
  end if;

  if p_resolution = 'not_created' then
    update public.order_claim_shipments
    set creation_status = 'failed', creation_token = null,
        creation_error = 'Conciliado: Andreani no creó la operación. Se puede volver a generar.',
        updated_at = clock_timestamp()
    where id = v_shipment.id returning * into v_shipment;
  else
    update public.order_claim_shipments
    set creation_status = 'created', status = 'generada', creation_token = null, creation_error = null,
        andreani_envio_id = btrim(p_envio_id),
        andreani_tracking = coalesce(nullif(btrim(coalesce(p_tracking, '')), ''), btrim(p_envio_id)),
        updated_at = clock_timestamp()
    where id = v_shipment.id returning * into v_shipment;
    perform public.order_claim_shipment_created_effects(v_shipment);
  end if;

  insert into public.order_audit_events (order_id, actor_type, actor_id, action, previous_status, new_status, metadata)
  values (v_shipment.order_id, 'admin', p_actor_id, 'claim_shipment_reconciled', 'manual_review', v_shipment.creation_status,
    jsonb_build_object('claimId', p_claim_id, 'direction', p_direction, 'resolution', p_resolution,
      'envioId', v_shipment.andreani_envio_id, 'notes', left(btrim(p_notes), 1000)));
  return v_shipment;
end;
$$;

-- 6. Tracking: avance monotónico y entrega única --------------------------

create or replace function public.apply_order_claim_shipment_tracking(
  p_claim_id bigint,
  p_direction text,
  p_phase text,
  p_estado text,
  p_tracking text,
  p_last_event text,
  p_last_event_at timestamptz
)
returns public.order_claim_shipments
language plpgsql
security definer
set search_path = public
as $$
declare
  v_shipment public.order_claim_shipments%rowtype;
  v_next text;
  v_delivered_now boolean := false;
begin
  if auth.role() is distinct from 'service_role' then raise exception 'FORBIDDEN' using errcode = '42501'; end if;
  if p_phase not in ('sin_cambio', 'en_transito', 'entregada', 'incidencia') then raise exception 'CLAIM_SHIPMENT_INVALID'; end if;

  select * into v_shipment from public.order_claim_shipments
  where claim_id = p_claim_id and direction = p_direction for update;
  if not found then raise exception 'CLAIM_SHIPMENT_NOT_FOUND'; end if;
  if v_shipment.creation_status is distinct from 'created' then raise exception 'CLAIM_SHIPMENT_NOT_CREATED'; end if;

  v_next := v_shipment.status;
  if v_shipment.status <> 'entregada' then
    if p_phase = 'entregada' then
      v_next := 'entregada';
      v_delivered_now := true;
    elsif p_phase = 'en_transito' and v_shipment.status in ('generada', 'incidencia') then
      v_next := 'en_transito';
    elsif p_phase = 'incidencia' then
      v_next := 'incidencia';
    end if;
  end if;

  update public.order_claim_shipments
  set status = v_next,
      delivered_at = case when v_delivered_now then clock_timestamp() else delivered_at end,
      andreani_estado = coalesce(nullif(btrim(coalesce(p_estado, '')), ''), andreani_estado),
      andreani_tracking = coalesce(andreani_tracking, nullif(btrim(coalesce(p_tracking, '')), '')),
      andreani_last_event = coalesce(nullif(btrim(coalesce(p_last_event, '')), ''), andreani_last_event),
      andreani_last_event_at = coalesce(p_last_event_at, andreani_last_event_at),
      last_checked_at = clock_timestamp(),
      updated_at = clock_timestamp()
  where id = v_shipment.id
  returning * into v_shipment;

  if v_delivered_now then
    -- Una sola vez. Primero el mensaje al cliente: sync_order_claim_admin_attention
    -- apaga admin_needs_action ante un mensaje de BEYONIX, y el aviso al Admin
    -- tiene que quedar (recepción física o cierre del reclamo).
    insert into public.order_claim_messages (claim_id, author_user_id, author_role, message, system_key)
    values (p_claim_id, null, 'admin',
      case p_direction
        when 'devolucion' then 'Andreani entregó tu producto en BEYONIX. Vamos a revisarlo y te avisaremos por este medio cómo sigue el cambio.'
        else 'Andreani informó que tu producto de reemplazo fue entregado.'
      end,
      case p_direction when 'devolucion' then 'return_received' else 'replacement_delivered' end)
    on conflict (claim_id, system_key) where system_key is not null do nothing;
    update public.order_claims set admin_needs_action = true where id = p_claim_id;
    insert into public.order_audit_events (order_id, actor_type, action, previous_status, new_status, metadata)
    values (v_shipment.order_id, 'system', 'claim_shipment_delivered', null, 'entregada',
      jsonb_build_object('claimId', p_claim_id, 'direction', p_direction,
        'envioId', v_shipment.andreani_envio_id, 'tracking', v_shipment.andreani_tracking, 'event', p_last_event));
  end if;
  return v_shipment;
end;
$$;

revoke all on function public.claim_order_claim_shipment_creation(bigint, text, uuid, text, text, text) from public, anon, authenticated;
revoke all on function public.complete_order_claim_shipment_creation(bigint, text, uuid, text, text, text, numeric) from public, anon, authenticated;
revoke all on function public.fail_order_claim_shipment_creation(bigint, text, uuid, text, text) from public, anon, authenticated;
revoke all on function public.resolve_order_claim_shipment_reconciliation(bigint, text, uuid, text, text, text, text) from public, anon, authenticated;
revoke all on function public.apply_order_claim_shipment_tracking(bigint, text, text, text, text, text, timestamptz) from public, anon, authenticated;
grant execute on function public.claim_order_claim_shipment_creation(bigint, text, uuid, text, text, text) to service_role;
grant execute on function public.complete_order_claim_shipment_creation(bigint, text, uuid, text, text, text, numeric) to service_role;
grant execute on function public.fail_order_claim_shipment_creation(bigint, text, uuid, text, text) to service_role;
grant execute on function public.resolve_order_claim_shipment_reconciliation(bigint, text, uuid, text, text, text, text) to service_role;
grant execute on function public.apply_order_claim_shipment_tracking(bigint, text, text, text, text, text, timestamptz) to service_role;

notify pgrst, 'reload schema';

commit;
