-- Operational dispatch layer. Andreani's per-order shipment and tracking stay authoritative.
-- All mutations are service_role RPCs with a verified operator; customer order state is unchanged.

alter table public.ordenes
  add column if not exists andreani_handed_over_at timestamptz,
  add column if not exists andreani_handed_over_by uuid,
  add column if not exists andreani_handed_over_batch_id bigint;

create table public.order_packages (
  id bigint generated by default as identity primary key,
  order_id bigint not null unique references public.ordenes(id) on delete restrict,
  status text not null default 'preparing' check (status in ('preparing','prepared')),
  attempt_number integer not null default 1 check (attempt_number > 0),
  prepared_by uuid,
  prepared_at timestamptz,
  created_at timestamptz not null default now(),
  check ((status = 'prepared') = (prepared_at is not null and prepared_by is not null))
);

create table public.order_preparation_lines (
  package_id bigint not null references public.order_packages(id) on delete restrict,
  order_item_id bigint not null unique references public.orden_items(id) on delete restrict,
  product_id bigint not null references public.productos(id) on delete restrict,
  variant_id bigint references public.producto_variantes(id) on delete restrict,
  conditioned_stock_id uuid,
  expected_sku text,
  expected_barcode text,
  expected_quantity integer not null check (expected_quantity > 0),
  scanned_quantity integer not null default 0 check (scanned_quantity >= 0),
  primary key (package_id, order_item_id),
  check (scanned_quantity <= expected_quantity),
  check (expected_sku is not null or expected_barcode is not null)
);

create table public.order_preparation_scans (
  id bigint generated by default as identity primary key,
  package_id bigint not null references public.order_packages(id) on delete restrict,
  attempt_number integer not null check (attempt_number > 0),
  order_item_id bigint not null references public.orden_items(id) on delete restrict,
  request_key uuid not null,
  code text not null,
  scanned_by uuid not null,
  scanned_at timestamptz not null default now(),
  unique (package_id, attempt_number, request_key),
  foreign key (package_id, order_item_id)
    references public.order_preparation_lines(package_id, order_item_id) on delete restrict
);

create table public.order_preparation_resets (
  id bigint generated by default as identity primary key,
  package_id bigint not null references public.order_packages(id) on delete restrict,
  request_key uuid not null,
  attempt_number integer not null check (attempt_number > 1),
  actor_id uuid not null,
  reason text not null check (length(btrim(reason)) >= 10),
  created_at timestamptz not null default now(),
  unique (package_id, request_key),
  unique (package_id, attempt_number)
);

create table public.dispatch_batch_day_sequences (
  dispatch_date date primary key,
  last_number integer not null check (last_number > 0)
);

create table public.dispatch_batches (
  id bigint generated by default as identity primary key,
  code text not null unique check (code ~ '^DSP-[0-9]{8}-[0-9]{3,}$'),
  request_key uuid not null unique,
  status text not null default 'open' check (status in ('open','closed','handed_over')),
  created_by uuid not null,
  created_at timestamptz not null default now(),
  closed_by uuid,
  closed_at timestamptz,
  handed_over_by uuid,
  handed_over_at timestamptz,
  check ((status = 'open' and closed_at is null and handed_over_at is null)
      or (status = 'closed' and closed_at is not null and handed_over_at is null)
      or (status = 'handed_over' and closed_at is not null and handed_over_at is not null)),
  check ((closed_at is null) = (closed_by is null)),
  check ((handed_over_at is null) = (handed_over_by is null))
);

alter table public.ordenes add constraint ordenes_handed_over_batch_fk
  foreign key (andreani_handed_over_batch_id) references public.dispatch_batches(id) on delete restrict;
alter table public.ordenes add constraint ordenes_handed_over_pair_check
  check ((andreani_handed_over_at is null and andreani_handed_over_batch_id is null and andreani_handed_over_by is null)
      or (andreani_handed_over_at is not null and andreani_handed_over_batch_id is not null and andreani_handed_over_by is not null));

create table public.dispatch_batch_items (
  id bigint generated by default as identity primary key,
  batch_id bigint not null references public.dispatch_batches(id) on delete restrict,
  package_id bigint not null references public.order_packages(id) on delete restrict,
  order_id bigint not null references public.ordenes(id) on delete restrict,
  added_by uuid not null,
  added_at timestamptz not null default now(),
  removed_by uuid,
  removed_at timestamptz,
  removal_reason text,
  unique (batch_id, order_id),
  check ((removed_at is null and removed_by is null and removal_reason is null)
      or (removed_at is not null and removed_by is not null and length(btrim(removal_reason)) >= 10))
);
create unique index dispatch_batch_items_active_order_unique
  on public.dispatch_batch_items(order_id) where removed_at is null;
create unique index dispatch_batch_items_active_package_unique
  on public.dispatch_batch_items(package_id) where removed_at is null;
create index dispatch_batch_items_active_batch_idx
  on public.dispatch_batch_items(batch_id) where removed_at is null;

create table public.dispatch_batch_events (
  id bigint generated by default as identity primary key,
  batch_id bigint not null references public.dispatch_batches(id) on delete restrict,
  actor_id uuid not null,
  action text not null check (action in ('created','order_added','closed','order_removed','handed_over')),
  order_id bigint references public.ordenes(id) on delete restrict,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index dispatch_batch_events_batch_idx on public.dispatch_batch_events(batch_id,created_at);

create table public.dispatch_blocks (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.ordenes(id) on delete restrict,
  reason text not null check (length(btrim(reason)) between 3 and 120),
  source text not null check (source in ('automatic','manual')),
  created_by uuid,
  created_at timestamptz not null default now(),
  resolved_by uuid,
  resolved_at timestamptz,
  resolution_reason text,
  check ((resolved_at is null and resolved_by is null and resolution_reason is null)
      or (resolved_at is not null and length(btrim(resolution_reason)) >= 10)),
  check (source <> 'manual' or created_by is not null)
);
create unique index dispatch_blocks_active_reason_unique
  on public.dispatch_blocks(order_id, source, reason) where resolved_at is null;
create index dispatch_blocks_active_order_idx
  on public.dispatch_blocks(order_id) where resolved_at is null;

alter table public.order_packages enable row level security;
alter table public.order_preparation_lines enable row level security;
alter table public.order_preparation_scans enable row level security;
alter table public.order_preparation_resets enable row level security;
alter table public.dispatch_batch_day_sequences enable row level security;
alter table public.dispatch_batches enable row level security;
alter table public.dispatch_batch_items enable row level security;
alter table public.dispatch_batch_events enable row level security;
alter table public.dispatch_blocks enable row level security;
revoke all on public.order_packages, public.order_preparation_lines,
  public.order_preparation_scans, public.order_preparation_resets,
  public.dispatch_batch_day_sequences,
  public.dispatch_batches, public.dispatch_batch_items, public.dispatch_blocks
  , public.dispatch_batch_events
  from public, anon, authenticated;
grant select on public.order_packages, public.order_preparation_lines,
  public.order_preparation_scans, public.order_preparation_resets, public.dispatch_batches,
  public.dispatch_batch_items, public.dispatch_blocks to service_role;
grant select on public.dispatch_batch_events to service_role;

create or replace function public.assert_dispatch_operator(p_actor_id uuid)
returns void language plpgsql security definer
set search_path = pg_catalog, public, pg_temp as $$
begin
  if auth.role() is distinct from 'service_role'
     or not exists (select 1 from public.profiles
                    where id = p_actor_id and rol in ('operador','admin','super_admin')) then
    raise exception 'DISPATCH_FORBIDDEN';
  end if;
end $$;

create or replace function public.reset_order_preparation(
  p_order_id bigint,p_actor_id uuid,p_request_key uuid,p_reason text)
returns public.order_packages language plpgsql security definer
set search_path = pg_catalog, public, pg_temp as $$
declare v_package public.order_packages%rowtype; v_item record;
  v_sku text; v_barcode text; v_snapshot jsonb;
  v_prior_reset public.order_preparation_resets%rowtype;
begin
  perform public.assert_dispatch_operator(p_actor_id);
  if p_request_key is null or length(btrim(coalesce(p_reason,'')))<10 then
    raise exception 'DISPATCH_RESET_REASON_REQUIRED'; end if;
  perform 1 from public.ordenes where id=p_order_id for update;
  select * into v_package from public.order_packages where order_id=p_order_id for update;
  if not found then raise exception 'DISPATCH_PREPARATION_NOT_STARTED'; end if;
  select * into v_prior_reset from public.order_preparation_resets
    where package_id=v_package.id and request_key=p_request_key;
  if found then
    if v_prior_reset.actor_id<>p_actor_id or v_prior_reset.reason<>left(btrim(p_reason),1000) then
      raise exception 'DISPATCH_RESET_KEY_CONFLICT'; end if;
    return v_package;
  end if;
  if exists (select 1 from public.dispatch_batch_items
             where order_id=p_order_id and removed_at is null)
     or exists (select 1 from public.ordenes
                where id=p_order_id and andreani_handed_over_at is not null) then
    raise exception 'DISPATCH_RESET_REQUIRES_REMOVAL'; end if;
  select coalesce(jsonb_agg(jsonb_build_object('itemId',order_item_id,
      'quantity',expected_quantity,'scanned',scanned_quantity,'sku',expected_sku)), '[]'::jsonb)
    into v_snapshot from public.order_preparation_lines where package_id=v_package.id;
  perform set_config('beyonix.dispatch_reset_order',p_order_id::text,true);
  update public.order_packages set status='preparing',prepared_at=null,prepared_by=null,
    attempt_number=attempt_number+1 where id=v_package.id returning * into v_package;
  for v_item in select i.*, p.sku product_sku, p.codigo_barra product_barcode,
      v.sku variant_sku, v.codigo_barra variant_barcode
    from public.orden_items i join public.productos p on p.id=i.producto_id
    left join public.producto_variantes v on v.id=i.variante_id
    where i.orden_id=p_order_id order by i.id loop
    v_sku := case when v_item.conditioned_stock_id is not null then v_item.conditioned_sku
                  when v_item.variante_id is not null then v_item.variant_sku
                  else v_item.product_sku end;
    v_barcode := case when v_item.conditioned_stock_id is not null then null
                      when v_item.variante_id is not null then v_item.variant_barcode
                      else v_item.product_barcode end;
    if v_item.cantidad<=0 or (nullif(btrim(coalesce(v_sku,'')),'') is null
        and nullif(btrim(coalesce(v_barcode,'')),'') is null) then
      raise exception 'DISPATCH_ITEM_IDENTITY_MISSING'; end if;
    insert into public.order_preparation_lines
      (package_id,order_item_id,product_id,variant_id,conditioned_stock_id,
       expected_sku,expected_barcode,expected_quantity,scanned_quantity)
    values (v_package.id,v_item.id,v_item.producto_id,v_item.variante_id,v_item.conditioned_stock_id,
      public.normalized_catalog_sku(v_sku),public.normalized_catalog_barcode(v_barcode),v_item.cantidad,0)
    on conflict (order_item_id) do update set
      product_id=excluded.product_id,variant_id=excluded.variant_id,
      conditioned_stock_id=excluded.conditioned_stock_id,
      expected_sku=excluded.expected_sku,expected_barcode=excluded.expected_barcode,
      expected_quantity=excluded.expected_quantity,scanned_quantity=0;
  end loop;
  if not found then raise exception 'DISPATCH_ORDER_EMPTY'; end if;
  insert into public.order_preparation_resets(package_id,request_key,attempt_number,actor_id,reason)
    values (v_package.id,p_request_key,v_package.attempt_number,p_actor_id,left(btrim(p_reason),1000));
  perform public.sync_dispatch_blocks(p_order_id);
  insert into public.order_audit_events(order_id,actor_type,actor_id,action,metadata)
    values (p_order_id,'admin',p_actor_id,'order_preparation_reset',
      jsonb_build_object('packageId',v_package.id,'attempt',v_package.attempt_number,
        'reason',left(btrim(p_reason),1000),'previousLines',v_snapshot));
  perform set_config('beyonix.dispatch_reset_order','',true);
  return v_package;
end $$;

-- This predicate is also used by the handover RPC, not merely by the UI or a trigger.
create or replace function public.dispatch_order_block_reasons(p_order_id bigint)
returns text[] language plpgsql stable security definer
set search_path = pg_catalog, public, pg_temp as $$
declare o public.ordenes%rowtype; v_reasons text[] := '{}';
begin
  select * into o from public.ordenes where id = p_order_id;
  if not found then raise exception 'DISPATCH_ORDER_NOT_FOUND'; end if;
  if o.paid_at is null and coalesce(o.payment_confirmed_amount,0) <= 0
     and coalesce(o.payment_status,'') not in ('confirmado','approved','confirmed')
     then v_reasons := array_append(v_reasons,'not_paid'); end if;
  if o.invoice_status is distinct from 'authorized' or o.invoice_cae is null
     then v_reasons := array_append(v_reasons,'invoice_pending'); end if;
  if o.estado = 'cancelado' or o.cancelled_at is not null
     then v_reasons := array_append(v_reasons,'cancelled'); end if;
  if o.financial_status is distinct from 'payment_confirmed'
     then v_reasons := array_append(v_reasons,'financial_conflict'); end if;
  if coalesce(o.payment_status,'') in ('rechazado','rejected','approved_amount_mismatch',
     'approved_currency_mismatch','approved_stock_conflict','approved_after_cancellation',
     'auto_verified_stock_conflict')
     then v_reasons := array_append(v_reasons,'payment_reversed'); end if;
  if o.order_change_status in ('change_requested','extra_payment_pending')
     then v_reasons := array_append(v_reasons,'change'); end if;
  if o.return_status in ('solicitada','en_revision','aprobada') and o.return_resolved_at is null
     then v_reasons := array_append(v_reasons,'return'); end if;
  if exists (select 1 from public.order_claims c where c.order_id = p_order_id
             and c.status not in ('cerrado','rechazado') and c.cancelled_at is null
             and c.failure_type <> 'consulta_pedido')
     then v_reasons := array_append(v_reasons,'claim'); end if;
  if exists (select 1 from public.order_packages p where p.order_id=p_order_id
      and (exists (select 1 from public.orden_items i
        left join public.order_preparation_lines l on l.package_id=p.id and l.order_item_id=i.id
        where i.orden_id=p_order_id and (l.order_item_id is null
          or l.product_id<>i.producto_id or l.variant_id is distinct from i.variante_id
          or l.conditioned_stock_id is distinct from i.conditioned_stock_id
          or l.expected_quantity<>i.cantidad))
      or exists (select 1 from public.order_preparation_lines l
        left join public.orden_items i on i.id=l.order_item_id and i.orden_id=p_order_id
        where l.package_id=p.id and i.id is null)))
     then v_reasons := array_append(v_reasons,'items_changed'); end if;
  if lower(coalesce(o.shipping_provider,o.envio_proveedor,'')) <> 'andreani'
     then v_reasons := array_append(v_reasons,'wrong_carrier'); end if;
  if o.andreani_envio_id is null or o.andreani_creation_status is distinct from 'created'
     then v_reasons := array_append(v_reasons,'shipment_pending'); end if;
  if o.andreani_creation_status in ('claimed','reconciliation_required')
     then v_reasons := array_append(v_reasons,'shipment_uncertain'); end if;
  if o.andreani_handed_over_at is not null
     then v_reasons := array_append(v_reasons,'already_handed_over'); end if;
  if o.andreani_tracking_event_at is not null or nullif(btrim(o.tracking_number),'') is not null
     or lower(coalesce(o.andreani_estado,'')) ~ '(camino|tránsito|transito|distribución|distribucion|reparto|visita|entregado)'
     or o.estado in
     ('enviado','en_camino','visita_fallida','en_sucursal','retiro_pendiente',
      'retiro_vencido','en_devolucion','devuelto_beyonix','entregado')
     then v_reasons := array_append(v_reasons,'tracking_in_circuit'); end if;
  if exists (select 1 from public.mercadopago_order_refunds r where r.order_id = p_order_id
             and r.status in ('requested','processing','needs_reconciliation'))
     then v_reasons := array_append(v_reasons,'refund_in_progress'); end if;
  return v_reasons;
end $$;

create or replace function public.sync_dispatch_blocks(p_order_id bigint)
returns void language plpgsql security definer
set search_path = pg_catalog, public, pg_temp as $$
declare v_reasons text[]; v_reason text;
begin
  -- Shared row lock serializes cancellation/claim/refund/dispatch transitions.
  perform 1 from public.ordenes where id = p_order_id for update;
  if not found then return; end if;
  if not exists (select 1 from public.order_packages where order_id = p_order_id) then return; end if;
  if exists (select 1 from public.ordenes where id = p_order_id and andreani_handed_over_at is not null) then
    update public.dispatch_blocks set resolved_at = now(), resolution_reason = 'Tanda entregada a Andreani'
      where order_id = p_order_id and source = 'automatic' and resolved_at is null;
    return;
  end if;
  v_reasons := public.dispatch_order_block_reasons(p_order_id);
  update public.dispatch_blocks set resolved_at = now(), resolution_reason = 'Condición operativa restablecida'
  where order_id = p_order_id and source = 'automatic' and resolved_at is null
    and not (reason = any(v_reasons));
  foreach v_reason in array v_reasons loop
    insert into public.dispatch_blocks(order_id, reason, source)
    values (p_order_id, v_reason, 'automatic') on conflict do nothing;
  end loop;
end $$;

create or replace function public.begin_order_preparation(p_order_id bigint, p_actor_id uuid)
returns public.order_packages language plpgsql security definer
set search_path = pg_catalog, public, pg_temp as $$
declare v_package public.order_packages%rowtype; v_item record; v_sku text; v_barcode text;
begin
  perform public.assert_dispatch_operator(p_actor_id);
  perform 1 from public.ordenes where id = p_order_id for update;
  if not found then raise exception 'DISPATCH_ORDER_NOT_FOUND'; end if;
  select * into v_package from public.order_packages where order_id = p_order_id for update;
  if found then return v_package; end if;
  -- Payment and customer holds block packing. Invoice and shipment may finish
  -- while BEYONIX is still preparing; they are mandatory before batch handover.
  if exists (select 1 from unnest(public.dispatch_order_block_reasons(p_order_id)) r
             where r not in ('invoice_pending','shipment_pending'))
     or exists (select 1 from public.dispatch_blocks where order_id=p_order_id
                and source='manual' and resolved_at is null) then
    raise exception 'DISPATCH_ORDER_BLOCKED';
  end if;
  insert into public.order_packages(order_id) values (p_order_id) returning * into v_package;
  for v_item in select i.*, p.sku product_sku, p.codigo_barra product_barcode,
      v.sku variant_sku, v.codigo_barra variant_barcode
    from public.orden_items i join public.productos p on p.id = i.producto_id
    left join public.producto_variantes v on v.id = i.variante_id
    where i.orden_id = p_order_id order by i.id loop
    v_sku := case when v_item.conditioned_stock_id is not null then v_item.conditioned_sku
                  when v_item.variante_id is not null then v_item.variant_sku
                  else v_item.product_sku end;
    v_barcode := case when v_item.conditioned_stock_id is not null then null
                      when v_item.variante_id is not null then v_item.variant_barcode
                      else v_item.product_barcode end;
    if v_item.cantidad <= 0 or (nullif(btrim(coalesce(v_sku,'')),'') is null
        and nullif(btrim(coalesce(v_barcode,'')),'') is null) then
      raise exception 'DISPATCH_ITEM_IDENTITY_MISSING';
    end if;
    insert into public.order_preparation_lines
      (package_id,order_item_id,product_id,variant_id,conditioned_stock_id,expected_sku,expected_barcode,expected_quantity)
    values (v_package.id,v_item.id,v_item.producto_id,v_item.variante_id,
      v_item.conditioned_stock_id, public.normalized_catalog_sku(v_sku),
      public.normalized_catalog_barcode(v_barcode),v_item.cantidad);
  end loop;
  if not found then raise exception 'DISPATCH_ORDER_EMPTY'; end if;
  perform public.sync_dispatch_blocks(p_order_id);
  insert into public.order_audit_events(order_id,actor_type,actor_id,action,metadata)
  values (p_order_id,'admin',p_actor_id,'order_preparation_started',jsonb_build_object('packageId',v_package.id));
  return v_package;
end $$;

create or replace function public.scan_order_preparation_item(
  p_order_id bigint, p_order_item_id bigint, p_code text, p_actor_id uuid, p_request_key uuid)
returns public.order_packages language plpgsql security definer
set search_path = pg_catalog, public, pg_temp as $$
declare v_package public.order_packages%rowtype; v_line public.order_preparation_lines%rowtype;
  v_existing_scan public.order_preparation_scans%rowtype;
  v_sku text; v_barcode text;
begin
  perform public.assert_dispatch_operator(p_actor_id);
  if p_request_key is null or nullif(btrim(coalesce(p_code,'')),'') is null then
    raise exception 'DISPATCH_SCAN_INVALID'; end if;
  select * into v_package from public.order_packages where order_id = p_order_id for update;
  if not found then raise exception 'DISPATCH_PREPARATION_NOT_STARTED'; end if;
  select * into v_existing_scan from public.order_preparation_scans
    where package_id = v_package.id and attempt_number=v_package.attempt_number
      and request_key = p_request_key;
  if found then
    if v_existing_scan.order_item_id <> p_order_item_id or v_existing_scan.code <> btrim(p_code) then
      raise exception 'DISPATCH_SCAN_KEY_CONFLICT'; end if;
    return v_package;
  end if;
  if v_package.status <> 'preparing' then raise exception 'DISPATCH_ALREADY_PREPARED'; end if;
  if exists (select 1 from unnest(public.dispatch_order_block_reasons(p_order_id)) r
             where r not in ('invoice_pending','shipment_pending'))
     or exists (select 1 from public.dispatch_blocks where order_id=p_order_id
                and source='manual' and resolved_at is null) then raise exception 'DISPATCH_ORDER_BLOCKED'; end if;
  select * into v_line from public.order_preparation_lines
    where package_id = v_package.id and order_item_id = p_order_item_id for update;
  if not found then raise exception 'DISPATCH_WRONG_ITEM'; end if;
  v_sku := public.normalized_catalog_sku(p_code);
  v_barcode := public.normalized_catalog_barcode(p_code);
  if (v_line.expected_sku is distinct from v_sku or v_line.expected_sku is null)
     and (v_line.expected_barcode is distinct from v_barcode or v_line.expected_barcode is null)
     then raise exception 'DISPATCH_WRONG_SKU_OR_VARIANT'; end if;
  if v_line.scanned_quantity >= v_line.expected_quantity then raise exception 'DISPATCH_QUANTITY_EXCEEDED'; end if;
  update public.order_preparation_lines set scanned_quantity = scanned_quantity + 1
    where package_id = v_package.id and order_item_id = p_order_item_id;
  insert into public.order_preparation_scans(package_id,attempt_number,order_item_id,request_key,code,scanned_by)
    values (v_package.id,v_package.attempt_number,p_order_item_id,p_request_key,btrim(p_code),p_actor_id);
  if not exists (select 1 from public.order_preparation_lines
                 where package_id = v_package.id and scanned_quantity <> expected_quantity) then
    update public.order_packages set status = 'prepared', prepared_at = now(), prepared_by = p_actor_id
      where id = v_package.id returning * into v_package;
    insert into public.order_audit_events(order_id,actor_type,actor_id,action,metadata)
      values (p_order_id,'admin',p_actor_id,'order_prepared',jsonb_build_object('packageId',v_package.id));
  end if;
  return v_package;
end $$;

create or replace function public.create_dispatch_batch(p_actor_id uuid, p_request_key uuid)
returns public.dispatch_batches language plpgsql security definer
set search_path = pg_catalog, public, pg_temp as $$
declare v_batch public.dispatch_batches%rowtype; v_date date; v_number integer;
begin
  perform public.assert_dispatch_operator(p_actor_id);
  if p_request_key is null then raise exception 'DISPATCH_REQUEST_KEY_REQUIRED'; end if;
  perform pg_advisory_xact_lock(hashtextextended(p_request_key::text, 0));
  select * into v_batch from public.dispatch_batches where request_key = p_request_key;
  if found then return v_batch; end if;
  v_date := (now() at time zone 'America/Argentina/Buenos_Aires')::date;
  insert into public.dispatch_batch_day_sequences(dispatch_date,last_number) values (v_date,1)
    on conflict (dispatch_date) do update set last_number = public.dispatch_batch_day_sequences.last_number + 1
    returning last_number into v_number;
  insert into public.dispatch_batches(code,request_key,created_by)
    values ('DSP-' || to_char(v_date,'YYYYMMDD') || '-' || lpad(v_number::text,3,'0'),p_request_key,p_actor_id)
    returning * into v_batch;
  insert into public.dispatch_batch_events(batch_id,actor_id,action)
    values (v_batch.id,p_actor_id,'created');
  return v_batch;
end $$;

create or replace function public.add_order_to_dispatch_batch(p_batch_id bigint,p_order_id bigint,p_actor_id uuid)
returns public.dispatch_batch_items language plpgsql security definer
set search_path = pg_catalog, public, pg_temp as $$
declare v_batch public.dispatch_batches%rowtype; v_package public.order_packages%rowtype;
  v_item public.dispatch_batch_items%rowtype;
begin
  perform public.assert_dispatch_operator(p_actor_id);
  select * into v_batch from public.dispatch_batches where id = p_batch_id for update;
  if not found then raise exception 'DISPATCH_BATCH_NOT_FOUND'; end if;
  select * into v_item from public.dispatch_batch_items
    where batch_id = p_batch_id and order_id = p_order_id and removed_at is null;
  if found then return v_item; end if;
  if v_batch.status <> 'open' then raise exception 'DISPATCH_BATCH_CLOSED'; end if;
  perform 1 from public.ordenes where id = p_order_id for update;
  select * into v_package from public.order_packages where order_id = p_order_id for update;
  if not found or v_package.status <> 'prepared' then raise exception 'DISPATCH_PACKAGE_NOT_PREPARED'; end if;
  if cardinality(public.dispatch_order_block_reasons(p_order_id)) > 0
     or exists (select 1 from public.dispatch_blocks where order_id = p_order_id and resolved_at is null)
     then raise exception 'DISPATCH_ORDER_BLOCKED'; end if;
  insert into public.dispatch_batch_items(batch_id,package_id,order_id,added_by)
    values (p_batch_id,v_package.id,p_order_id,p_actor_id) returning * into v_item;
  insert into public.dispatch_batch_events(batch_id,actor_id,action,order_id)
    values (p_batch_id,p_actor_id,'order_added',p_order_id);
  insert into public.order_audit_events(order_id,actor_type,actor_id,action,metadata)
    values (p_order_id,'admin',p_actor_id,'order_added_to_dispatch_batch',jsonb_build_object('batchId',p_batch_id));
  return v_item;
end $$;

create or replace function public.close_dispatch_batch(p_batch_id bigint,p_actor_id uuid)
returns public.dispatch_batches language plpgsql security definer
set search_path = pg_catalog, public, pg_temp as $$
declare v_batch public.dispatch_batches%rowtype; v_item record;
begin
  perform public.assert_dispatch_operator(p_actor_id);
  select * into v_batch from public.dispatch_batches where id = p_batch_id for update;
  if not found then raise exception 'DISPATCH_BATCH_NOT_FOUND'; end if;
  if v_batch.status in ('closed','handed_over') then return v_batch; end if;
  if not exists (select 1 from public.dispatch_batch_items where batch_id = p_batch_id and removed_at is null)
     then raise exception 'DISPATCH_BATCH_EMPTY'; end if;
  for v_item in select order_id from public.dispatch_batch_items
    where batch_id = p_batch_id and removed_at is null order by order_id loop
    perform 1 from public.ordenes where id = v_item.order_id for update;
    if cardinality(public.dispatch_order_block_reasons(v_item.order_id)) > 0
       or exists (select 1 from public.dispatch_blocks where order_id = v_item.order_id and resolved_at is null)
       then raise exception 'DISPATCH_ORDER_BLOCKED'; end if;
  end loop;
  update public.dispatch_batches set status='closed',closed_at=now(),closed_by=p_actor_id
    where id=p_batch_id returning * into v_batch;
  insert into public.dispatch_batch_events(batch_id,actor_id,action)
    values (p_batch_id,p_actor_id,'closed');
  return v_batch;
end $$;

create or replace function public.remove_order_from_dispatch_batch(
  p_batch_id bigint,p_order_id bigint,p_actor_id uuid,p_reason text)
returns public.dispatch_batch_items language plpgsql security definer
set search_path = pg_catalog, public, pg_temp as $$
declare v_batch public.dispatch_batches%rowtype; v_item public.dispatch_batch_items%rowtype;
begin
  perform public.assert_dispatch_operator(p_actor_id);
  if length(btrim(coalesce(p_reason,''))) < 10 then raise exception 'DISPATCH_REASON_REQUIRED'; end if;
  select * into v_batch from public.dispatch_batches where id=p_batch_id for update;
  if not found then raise exception 'DISPATCH_BATCH_NOT_FOUND'; end if;
  select * into v_item from public.dispatch_batch_items
    where batch_id=p_batch_id and order_id=p_order_id for update;
  if not found then raise exception 'DISPATCH_ITEM_NOT_FOUND'; end if;
  if v_item.removed_at is not null then return v_item; end if;
  if v_batch.status='handed_over' then raise exception 'DISPATCH_ALREADY_HANDED_OVER'; end if;
  perform 1 from public.ordenes where id=p_order_id for update;
  update public.dispatch_batch_items set removed_by=p_actor_id,removed_at=now(),removal_reason=left(btrim(p_reason),1000)
    where id=v_item.id returning * into v_item;
  insert into public.dispatch_batch_events(batch_id,actor_id,action,order_id,metadata)
    values (p_batch_id,p_actor_id,'order_removed',p_order_id,jsonb_build_object('reason',v_item.removal_reason));
  insert into public.order_audit_events(order_id,actor_type,actor_id,action,metadata)
    values (p_order_id,'admin',p_actor_id,'order_removed_from_dispatch_batch',
      jsonb_build_object('batchId',p_batch_id,'reason',v_item.removal_reason));
  return v_item;
end $$;

create or replace function public.set_dispatch_manual_block(
  p_order_id bigint,p_actor_id uuid,p_reason text,p_block boolean)
returns public.dispatch_blocks language plpgsql security definer
set search_path = pg_catalog, public, pg_temp as $$
declare v_block public.dispatch_blocks%rowtype; v_reason text;
begin
  perform public.assert_dispatch_operator(p_actor_id);
  v_reason:=left(btrim(coalesce(p_reason,'')),120);
  if length(v_reason)<10 then raise exception 'DISPATCH_REASON_REQUIRED'; end if;
  perform 1 from public.ordenes where id=p_order_id for update;
  if not found then raise exception 'DISPATCH_ORDER_NOT_FOUND'; end if;
  if p_block and exists (select 1 from public.ordenes where id=p_order_id and andreani_handed_over_at is not null)
     then raise exception 'DISPATCH_ALREADY_HANDED_OVER'; end if;
  select * into v_block from public.dispatch_blocks
    where order_id=p_order_id and source='manual' and reason=v_reason and resolved_at is null for update;
  if p_block then
    if found then return v_block; end if;
    insert into public.dispatch_blocks(order_id,reason,source,created_by)
      values (p_order_id,v_reason,'manual',p_actor_id) returning * into v_block;
  else
    if not found then
      select * into v_block from public.dispatch_blocks
        where order_id=p_order_id and source='manual' and reason=v_reason
        order by created_at desc limit 1;
      if found and v_block.resolved_at is not null then return v_block; end if;
      raise exception 'DISPATCH_BLOCK_NOT_FOUND';
    end if;
    update public.dispatch_blocks set resolved_by=p_actor_id,resolved_at=now(),
      resolution_reason='Resuelto por administración: ' || v_reason
      where id=v_block.id returning * into v_block;
  end if;
  insert into public.order_audit_events(order_id,actor_type,actor_id,action,metadata)
    values (p_order_id,'admin',p_actor_id,
      case when p_block then 'dispatch_block_added' else 'dispatch_block_resolved' end,
      jsonb_build_object('blockId',v_block.id,'reason',v_reason));
  return v_block;
end $$;

create or replace function public.hand_over_dispatch_batch(p_batch_id bigint,p_actor_id uuid)
returns public.dispatch_batches language plpgsql security definer
set search_path = pg_catalog, public, pg_temp as $$
declare v_batch public.dispatch_batches%rowtype; v_item record; v_at timestamptz := now();
begin
  perform public.assert_dispatch_operator(p_actor_id);
  select * into v_batch from public.dispatch_batches where id=p_batch_id for update;
  if not found then raise exception 'DISPATCH_BATCH_NOT_FOUND'; end if;
  if v_batch.status='handed_over' then return v_batch; end if;
  if v_batch.status<>'closed' then raise exception 'DISPATCH_BATCH_NOT_CLOSED'; end if;
  if not exists (select 1 from public.dispatch_batch_items where batch_id=p_batch_id and removed_at is null)
     then raise exception 'DISPATCH_BATCH_EMPTY'; end if;
  -- Lock every order before checking. Cancellation and refund RPCs lock the same rows.
  for v_item in select i.order_id,i.package_id from public.dispatch_batch_items i
    where i.batch_id=p_batch_id and i.removed_at is null order by i.order_id loop
    perform 1 from public.ordenes where id=v_item.order_id for update;
    if cardinality(public.dispatch_order_block_reasons(v_item.order_id))>0
       or exists (select 1 from public.dispatch_blocks where order_id=v_item.order_id and resolved_at is null)
       or not exists (select 1 from public.order_packages
                      where id=v_item.package_id and order_id=v_item.order_id and status='prepared')
       then raise exception 'DISPATCH_ORDER_BLOCKED'; end if;
  end loop;
  update public.dispatch_batches set status='handed_over',handed_over_by=p_actor_id,
    handed_over_at=v_at where id=p_batch_id returning * into v_batch;
  insert into public.dispatch_batch_events(batch_id,actor_id,action)
    values (p_batch_id,p_actor_id,'handed_over');
  for v_item in select order_id from public.dispatch_batch_items
    where batch_id=p_batch_id and removed_at is null order by order_id loop
    update public.ordenes set andreani_handed_over_at=v_at,
      andreani_handed_over_by=p_actor_id,andreani_handed_over_batch_id=p_batch_id
      where id=v_item.order_id and andreani_handed_over_at is null;
    if not found then raise exception 'DISPATCH_ORDER_ALREADY_HANDED_OVER'; end if;
    insert into public.order_audit_events(order_id,actor_type,actor_id,action,metadata)
      values (v_item.order_id,'admin',p_actor_id,'order_handed_over_to_andreani',
        jsonb_build_object('batchId',p_batch_id,'batchCode',v_batch.code));
  end loop;
  return v_batch;
end $$;

revoke all on function public.assert_dispatch_operator(uuid),
  public.dispatch_order_block_reasons(bigint), public.sync_dispatch_blocks(bigint),
  public.begin_order_preparation(bigint,uuid),
  public.reset_order_preparation(bigint,uuid,uuid,text),
  public.scan_order_preparation_item(bigint,bigint,text,uuid,uuid),
  public.create_dispatch_batch(uuid,uuid),
  public.add_order_to_dispatch_batch(bigint,bigint,uuid),
  public.close_dispatch_batch(bigint,uuid),
  public.remove_order_from_dispatch_batch(bigint,bigint,uuid,text),
  public.set_dispatch_manual_block(bigint,uuid,text,boolean),
  public.hand_over_dispatch_batch(bigint,uuid) from public,anon,authenticated;
grant execute on function public.assert_dispatch_operator(uuid),
  public.dispatch_order_block_reasons(bigint), public.sync_dispatch_blocks(bigint),
  public.begin_order_preparation(bigint,uuid),
  public.reset_order_preparation(bigint,uuid,uuid,text),
  public.scan_order_preparation_item(bigint,bigint,text,uuid,uuid),
  public.create_dispatch_batch(uuid,uuid),
  public.add_order_to_dispatch_batch(bigint,bigint,uuid),
  public.close_dispatch_batch(bigint,uuid),
  public.remove_order_from_dispatch_batch(bigint,bigint,uuid,text),
  public.set_dispatch_manual_block(bigint,uuid,text,boolean),
  public.hand_over_dispatch_batch(bigint,uuid) to service_role;
