-- Conciliación logística Andreani: cotizado en checkout vs cotizado con bultos
-- reales vs facturado/liquidado por Andreani.
--
-- No existe (ni está documentada en docs/andreani) una API de facturación o
-- liquidación: los campos "factura" de las APIs de envío son la factura del
-- remitente, no lo que Andreani le cobra a BEYONIX. Por eso el facturado se
-- registra manualmente o se importa por CSV desde Admin → Logística. La
-- fuente 'api' queda reservada para una integración futura confirmada.
--
-- Modelo: un renglón por cargo facturado (andreani_billing_entries), con tipo
-- de movimiento (envío, devolución, cambio, reenvío, otro). Un pedido puede
-- tener varios cargos. Cada cargo guarda un snapshot de las cotizaciones del
-- pedido al momento de asociarse: la comparación histórica nunca se recalcula
-- con datos posteriores (por ejemplo, un rearmado que vuelve a cotizar).
--
-- Reemplaza a las columnas ordenes.andreani_billed_* (20261008100000), que
-- sólo admitían un importe por pedido y nunca se llenaron.

-- 1. Cargos facturados -----------------------------------------------------------
create table public.andreani_billing_entries (
  id bigint generated by default as identity primary key,
  order_id bigint references public.ordenes(id) on delete restrict,
  claim_shipment_id bigint references public.order_claim_shipments(id) on delete restrict,
  movement_type text not null check (movement_type in
    ('outbound', 'return', 'exchange_return', 'exchange_resend', 'other')),
  tracking text check (tracking is null or tracking ~ '^[A-Z0-9-]{4,64}$'),
  billed_amount numeric(12,2) not null check (billed_amount >= 0 and billed_amount < 100000000),
  billed_on date not null check (billed_on between date '2020-01-01' and date '2100-01-01'),
  invoice_reference text not null check (length(btrim(invoice_reference)) between 1 and 80),
  source text not null check (source in ('manual', 'csv', 'api')),
  notes text check (notes is null or length(notes) <= 1000),
  match_status text not null check (match_status in ('matched', 'unmatched')),
  unmatched_reason text check (unmatched_reason is null
    or unmatched_reason in ('not_found', 'ambiguous', 'no_tracking')),
  -- Cotizaciones del pedido al asociarse (con IVA, como el facturado).
  checkout_quote_snapshot numeric(12,2),
  parcel_quote_snapshot numeric(12,2),
  dedupe_key text not null unique,
  created_by uuid not null,
  created_at timestamptz not null default now(),
  updated_by uuid,
  updated_at timestamptz,
  correction_reason text check (correction_reason is null or length(btrim(correction_reason)) between 5 and 500),
  check ((match_status = 'matched') = (order_id is not null)),
  check ((match_status = 'unmatched') = (unmatched_reason is not null)),
  check (claim_shipment_id is null or order_id is not null)
);
create index andreani_billing_entries_order_idx on public.andreani_billing_entries(order_id);
create index andreani_billing_entries_tracking_idx on public.andreani_billing_entries(tracking);
create index andreani_billing_entries_billed_on_idx on public.andreani_billing_entries(billed_on);
comment on table public.andreani_billing_entries is
  'Importe facturado/liquidado realmente por Andreani, cargado desde la factura o liquidación (manual o CSV). Nunca se infiere de una cotización.';

alter table public.andreani_billing_entries enable row level security;
revoke all on public.andreani_billing_entries from public, anon, authenticated;
grant select, insert, update on public.andreani_billing_entries to service_role;
grant usage on sequence public.andreani_billing_entries_id_seq to service_role;

-- Cada alta y corrección queda en audit_logs (antes/después completos).
create trigger andreani_billing_entries_audit_log_trigger
  after insert or update or delete on public.andreani_billing_entries
  for each row execute function public.audit_log_change();

comment on column public.ordenes.andreani_billed_amount is
  'Obsoleta: reemplazada por andreani_billing_entries (varios cargos por pedido). No se lee ni se escribe.';

-- 2. Reglas centralizadas ---------------------------------------------------------
-- Umbrales únicos para la UI y los resúmenes (la UI los recibe del resumen).
-- Facturado vs referencia (cotización con bultos reales si existe; si no, la
-- de checkout), ambos con IVA:
--   conciliado: |dif| < $100 (redondeos)
--   importante: |dif| >= $500 (mismo mínimo que la alerta de recotización) o >= 5 %
--   menor: el resto
create or replace function public.andreani_reconciliation_thresholds()
returns jsonb language sql immutable
set search_path = pg_catalog, public, pg_temp as $$
  select jsonb_build_object('reconciledAmount', 100, 'majorAmount', 500, 'majorPercent', 5)
$$;

create or replace function public.andreani_reconciliation_status(
  p_billed numeric, p_reference numeric)
returns text language sql immutable
set search_path = pg_catalog, public, pg_temp as $$
  select case
    when p_billed is null then 'pending'
    when p_reference is null or p_reference <= 0 then 'no_reference'
    when abs(p_billed - p_reference) < (public.andreani_reconciliation_thresholds() ->> 'reconciledAmount')::numeric
      then 'reconciled'
    when abs(p_billed - p_reference) >= (public.andreani_reconciliation_thresholds() ->> 'majorAmount')::numeric
      or abs(p_billed - p_reference) * 100 / p_reference
         >= (public.andreani_reconciliation_thresholds() ->> 'majorPercent')::numeric
      then 'major_difference'
    else 'minor_difference'
  end
$$;

-- 3. Permisos ---------------------------------------------------------------------
create or replace function public.assert_logistics_admin(p_actor_id uuid)
returns void language plpgsql security definer
set search_path = pg_catalog, public, pg_temp as $$
begin
  if auth.role() is distinct from 'service_role'
     or not exists (select 1 from public.profiles
                    where id = p_actor_id and rol in ('admin', 'super_admin')) then
    raise exception 'LOGISTICS_FORBIDDEN';
  end if;
end $$;

-- 4. Matching por tracking ----------------------------------------------------------
-- Sólo asocia si el tracking identifica UN envío: el de un pedido o el de un
-- envío de reclamo (devolución/reemplazo). Nunca adivina por importe o fecha.
create or replace function public.andreani_billing_match(p_tracking text)
returns table(order_id bigint, claim_shipment_id bigint, movement_type text, candidates integer)
language sql stable security definer
set search_path = pg_catalog, public, pg_temp as $$
  with targets as (
    select o.id as order_id, null::bigint as claim_shipment_id, 'outbound'::text as movement_type
    from public.ordenes o
    where p_tracking is not null
      and p_tracking in (upper(btrim(o.andreani_tracking)), upper(btrim(o.tracking_number)), upper(btrim(o.andreani_envio_id)))
    union
    select s.order_id, s.id,
      case when s.direction = 'reemplazo' then 'exchange_resend'
           when exists (select 1 from public.order_claim_shipments r
                        where r.claim_id = s.claim_id and r.direction = 'reemplazo') then 'exchange_return'
           else 'return' end
    from public.order_claim_shipments s
    where p_tracking is not null
      and p_tracking in (upper(btrim(s.andreani_tracking)), upper(btrim(s.andreani_envio_id)))
  )
  select t.order_id, t.claim_shipment_id, t.movement_type, (select count(*)::integer from targets)
  from targets t
  limit 1
$$;

-- 5. Alta (manual o importación) ---------------------------------------------------
-- p_entries: [{ orderId?, tracking?, amount, billedOn (YYYY-MM-DD), reference,
--   movementType?, notes? }]. orderId sólo en la carga manual por pedido.
-- Idempotente por dedupe_key = referencia + (tracking | pedido | fila) + tipo:
-- la misma línea de factura cargada dos veces (aunque sea por otra fuente)
-- no duplica; si difiere en importe o fecha se informa conflicto y no se pisa.
-- p_dry_run: valida y simula el matching sin escribir (vista previa del CSV).
create or replace function public.record_andreani_billing_entries(
  p_entries jsonb, p_source text, p_actor_id uuid, p_dry_run boolean default false)
returns jsonb language plpgsql security definer
set search_path = pg_catalog, public, pg_temp as $$
declare
  v_entry jsonb;
  v_index integer := -1;
  v_results jsonb := '[]'::jsonb;
  v_order_id bigint;
  v_claim_shipment_id bigint;
  v_movement text;
  v_tracking text;
  v_amount numeric;
  v_billed_on date;
  v_reference text;
  v_notes text;
  v_match record;
  v_reason text;
  v_key text;
  v_existing public.andreani_billing_entries%rowtype;
  v_order public.ordenes%rowtype;
  v_saved public.andreani_billing_entries%rowtype;
  v_seen text[] := '{}';
begin
  perform public.assert_logistics_admin(p_actor_id);
  if p_source not in ('manual', 'csv') then raise exception 'BILLING_SOURCE_INVALID'; end if;
  if p_entries is null or jsonb_typeof(p_entries) <> 'array'
     or jsonb_array_length(p_entries) = 0 or jsonb_array_length(p_entries) > 2000 then
    raise exception 'BILLING_ENTRIES_INVALID';
  end if;

  for v_entry in select value from jsonb_array_elements(p_entries) loop
    v_index := v_index + 1;
    v_order_id := null; v_claim_shipment_id := null; v_reason := null; v_movement := null;
    begin
      if jsonb_typeof(v_entry) <> 'object' then raise exception 'BILLING_ROW_INVALID'; end if;
      v_tracking := nullif(upper(regexp_replace(coalesce(v_entry ->> 'tracking', ''), '\s', '', 'g')), '');
      if v_tracking is not null and v_tracking !~ '^[A-Z0-9-]{4,64}$' then raise exception 'BILLING_TRACKING_INVALID'; end if;
      if coalesce(v_entry ->> 'amount', '') !~ '^[0-9]{1,8}(\.[0-9]{1,2})?$' then raise exception 'BILLING_AMOUNT_INVALID'; end if;
      v_amount := (v_entry ->> 'amount')::numeric;
      if coalesce(v_entry ->> 'billedOn', '') !~ '^\d{4}-\d{2}-\d{2}$' then raise exception 'BILLING_DATE_INVALID'; end if;
      begin
        v_billed_on := (v_entry ->> 'billedOn')::date;
      exception when others then raise exception 'BILLING_DATE_INVALID';
      end;
      if v_billed_on < date '2020-01-01' or v_billed_on > current_date + 31 then raise exception 'BILLING_DATE_INVALID'; end if;
      v_reference := btrim(coalesce(v_entry ->> 'reference', ''));
      if length(v_reference) not between 1 and 80 then raise exception 'BILLING_REFERENCE_INVALID'; end if;
      v_notes := nullif(btrim(coalesce(v_entry ->> 'notes', '')), '');
      if length(v_notes) > 1000 then raise exception 'BILLING_NOTES_INVALID'; end if;
      v_movement := nullif(v_entry ->> 'movementType', '');
      if v_movement is not null and v_movement not in
         ('outbound', 'return', 'exchange_return', 'exchange_resend', 'other') then
        raise exception 'BILLING_MOVEMENT_INVALID';
      end if;

      if v_entry ? 'orderId' and v_entry ->> 'orderId' is not null then
        -- Carga manual desde el pedido: la asociación la decide el Admin.
        if p_source <> 'manual' or (v_entry ->> 'orderId') !~ '^[0-9]{1,18}$' then raise exception 'BILLING_ROW_INVALID'; end if;
        v_order_id := (v_entry ->> 'orderId')::bigint;
        if not exists (select 1 from public.ordenes where id = v_order_id) then raise exception 'BILLING_ORDER_NOT_FOUND'; end if;
        if v_tracking is not null then
          select * into v_match from public.andreani_billing_match(v_tracking);
          if found and v_match.candidates = 1 then
            if v_match.order_id <> v_order_id then raise exception 'BILLING_TRACKING_OTHER_ORDER'; end if;
            v_claim_shipment_id := v_match.claim_shipment_id;
            v_movement := coalesce(v_movement, v_match.movement_type);
          end if;
        end if;
        v_movement := coalesce(v_movement, 'outbound');
      elsif v_tracking is null then
        v_reason := 'no_tracking';
      else
        select * into v_match from public.andreani_billing_match(v_tracking);
        if not found then v_reason := 'not_found';
        elsif v_match.candidates > 1 then v_reason := 'ambiguous';
        else
          v_order_id := v_match.order_id;
          v_claim_shipment_id := v_match.claim_shipment_id;
          -- El tipo del envío encontrado manda: un tracking de devolución no
          -- puede cargarse como envío original.
          v_movement := v_match.movement_type;
        end if;
      end if;
      v_movement := coalesce(v_movement, 'other');

      v_key := lower(v_reference) || '|' || coalesce(v_tracking, 'order:' || v_order_id::text,
        'row:' || v_amount::text || ':' || v_billed_on::text) || '|' || v_movement;
      perform pg_advisory_xact_lock(93010, hashtext(v_key));
      select * into v_existing from public.andreani_billing_entries where dedupe_key = v_key;
      if found then
        v_results := v_results || jsonb_build_object('index', v_index,
          'status', case when v_existing.billed_amount = v_amount and v_existing.billed_on = v_billed_on
                         then 'duplicate' else 'conflict' end,
          'entryId', v_existing.id, 'orderId', v_existing.order_id,
          'matchStatus', v_existing.match_status, 'movementType', v_existing.movement_type);
        continue;
      end if;

      if v_order_id is not null then
        select * into v_order from public.ordenes where id = v_order_id;
      end if;
      if p_dry_run then
        -- Vista previa: una fila repetida dentro del mismo archivo también es duplicado.
        if v_key = any(v_seen) then
          v_results := v_results || jsonb_build_object('index', v_index, 'status', 'duplicate',
            'orderId', v_order_id, 'movementType', v_movement);
          continue;
        end if;
        v_seen := array_append(v_seen, v_key);
        v_results := v_results || jsonb_build_object('index', v_index, 'status', 'ready',
          'orderId', v_order_id, 'matchStatus', case when v_order_id is null then 'unmatched' else 'matched' end,
          'unmatchedReason', v_reason, 'movementType', v_movement);
        continue;
      end if;
      insert into public.andreani_billing_entries (order_id, claim_shipment_id, movement_type, tracking,
        billed_amount, billed_on, invoice_reference, source, notes, match_status, unmatched_reason,
        checkout_quote_snapshot, parcel_quote_snapshot, dedupe_key, created_by)
      values (v_order_id, v_claim_shipment_id, v_movement, v_tracking, v_amount, v_billed_on, v_reference,
        p_source, v_notes, case when v_order_id is null then 'unmatched' else 'matched' end, v_reason,
        case when v_order_id is not null then v_order.shipping_provider_quote_amount end,
        case when v_order_id is not null and v_order.shipping_parcel_quote_status = 'quoted'
             then v_order.shipping_parcel_quote_amount end,
        v_key, p_actor_id)
      returning * into v_saved;
      v_results := v_results || jsonb_build_object('index', v_index, 'status', 'created',
        'entryId', v_saved.id, 'orderId', v_saved.order_id, 'matchStatus', v_saved.match_status,
        'unmatchedReason', v_saved.unmatched_reason, 'movementType', v_saved.movement_type);
    exception
      when raise_exception then
        if sqlerrm not like 'BILLING_%' then raise; end if;
        v_results := v_results || jsonb_build_object('index', v_index, 'status', 'invalid', 'error', sqlerrm);
    end;
  end loop;
  return v_results;
end $$;

-- 6. Corrección auditada -------------------------------------------------------------
-- Cambia importe/fecha/referencia/tipo/observación, o asocia a un pedido un
-- cargo "Sin pedido asociado" (decisión explícita del Admin). Exige motivo.
-- El snapshot de cotizaciones sólo se toma al asociar; nunca se recalcula.
create or replace function public.update_andreani_billing_entry(
  p_entry_id bigint, p_patch jsonb, p_reason text, p_actor_id uuid)
returns public.andreani_billing_entries language plpgsql security definer
set search_path = pg_catalog, public, pg_temp as $$
declare
  v_entry public.andreani_billing_entries%rowtype;
  v_order public.ordenes%rowtype;
  v_key text;
begin
  perform public.assert_logistics_admin(p_actor_id);
  if p_patch is null or jsonb_typeof(p_patch) <> 'object' then raise exception 'BILLING_ROW_INVALID'; end if;
  if length(btrim(coalesce(p_reason, ''))) not between 5 and 500 then raise exception 'BILLING_REASON_REQUIRED'; end if;
  select * into v_entry from public.andreani_billing_entries where id = p_entry_id for update;
  if not found then raise exception 'BILLING_ENTRY_NOT_FOUND'; end if;

  if p_patch ? 'amount' then
    if coalesce(p_patch ->> 'amount', '') !~ '^[0-9]{1,8}(\.[0-9]{1,2})?$' then raise exception 'BILLING_AMOUNT_INVALID'; end if;
    v_entry.billed_amount := (p_patch ->> 'amount')::numeric;
  end if;
  if p_patch ? 'billedOn' then
    if coalesce(p_patch ->> 'billedOn', '') !~ '^\d{4}-\d{2}-\d{2}$' then raise exception 'BILLING_DATE_INVALID'; end if;
    v_entry.billed_on := (p_patch ->> 'billedOn')::date;
    if v_entry.billed_on < date '2020-01-01' or v_entry.billed_on > current_date + 31 then raise exception 'BILLING_DATE_INVALID'; end if;
  end if;
  if p_patch ? 'reference' then
    v_entry.invoice_reference := btrim(coalesce(p_patch ->> 'reference', ''));
    if length(v_entry.invoice_reference) not between 1 and 80 then raise exception 'BILLING_REFERENCE_INVALID'; end if;
  end if;
  if p_patch ? 'notes' then
    v_entry.notes := nullif(btrim(coalesce(p_patch ->> 'notes', '')), '');
    if length(v_entry.notes) > 1000 then raise exception 'BILLING_NOTES_INVALID'; end if;
  end if;
  if p_patch ? 'movementType' then
    v_entry.movement_type := p_patch ->> 'movementType';
    if v_entry.movement_type is null or v_entry.movement_type not in
       ('outbound', 'return', 'exchange_return', 'exchange_resend', 'other') then
      raise exception 'BILLING_MOVEMENT_INVALID';
    end if;
  end if;
  if p_patch ? 'orderId' then
    if v_entry.order_id is not null then raise exception 'BILLING_ALREADY_MATCHED'; end if;
    if coalesce(p_patch ->> 'orderId', '') !~ '^[0-9]{1,18}$' then raise exception 'BILLING_ROW_INVALID'; end if;
    select * into v_order from public.ordenes where id = (p_patch ->> 'orderId')::bigint;
    if not found then raise exception 'BILLING_ORDER_NOT_FOUND'; end if;
    v_entry.order_id := v_order.id;
    v_entry.match_status := 'matched';
    v_entry.unmatched_reason := null;
    v_entry.checkout_quote_snapshot := v_order.shipping_provider_quote_amount;
    v_entry.parcel_quote_snapshot := case when v_order.shipping_parcel_quote_status = 'quoted'
      then v_order.shipping_parcel_quote_amount end;
  end if;

  v_key := lower(v_entry.invoice_reference) || '|' || coalesce(v_entry.tracking, 'order:' || v_entry.order_id::text,
    'row:' || v_entry.billed_amount::text || ':' || v_entry.billed_on::text) || '|' || v_entry.movement_type;
  if v_key <> v_entry.dedupe_key then
    perform pg_advisory_xact_lock(93010, hashtext(v_key));
    if exists (select 1 from public.andreani_billing_entries where dedupe_key = v_key and id <> v_entry.id) then
      raise exception 'BILLING_DUPLICATE';
    end if;
  end if;

  update public.andreani_billing_entries set
    order_id = v_entry.order_id, match_status = v_entry.match_status,
    unmatched_reason = v_entry.unmatched_reason, movement_type = v_entry.movement_type,
    billed_amount = v_entry.billed_amount, billed_on = v_entry.billed_on,
    invoice_reference = v_entry.invoice_reference, notes = v_entry.notes,
    checkout_quote_snapshot = v_entry.checkout_quote_snapshot,
    parcel_quote_snapshot = v_entry.parcel_quote_snapshot,
    dedupe_key = v_key, updated_by = p_actor_id, updated_at = now(),
    correction_reason = btrim(p_reason)
  where id = v_entry.id
  returning * into v_entry;
  return v_entry;
end $$;

-- 7. Conciliación por pedido ------------------------------------------------------
-- Referencia de comparación: el snapshot del último cargo de envío original
-- (cotización con bultos reales si había; si no, la de checkout). Los cargos
-- de devolución/cambio/reenvío se informan aparte y no alteran el estado del
-- envío original.
create or replace function public.andreani_order_reconciliation(p_order_ids bigint[])
returns table(order_id bigint, billed_outbound numeric, billed_return numeric,
  billed_exchange numeric, billed_other numeric, billed_total numeric, entries integer,
  checkout_quote numeric, parcel_quote numeric, reference_amount numeric,
  difference_checkout numeric, difference_parcel numeric, status text, references_list text)
language sql stable security definer
set search_path = pg_catalog, public, pg_temp as $$
  with per_order as (
    select e.order_id,
      sum(e.billed_amount) filter (where e.movement_type = 'outbound') as billed_outbound,
      sum(e.billed_amount) filter (where e.movement_type = 'return') as billed_return,
      sum(e.billed_amount) filter (where e.movement_type in ('exchange_return', 'exchange_resend')) as billed_exchange,
      sum(e.billed_amount) filter (where e.movement_type = 'other') as billed_other,
      sum(e.billed_amount) as billed_total,
      count(*)::integer as entries,
      (array_agg(e.checkout_quote_snapshot order by e.id desc) filter (where e.movement_type = 'outbound'))[1] as checkout_quote,
      (array_agg(e.parcel_quote_snapshot order by e.id desc) filter (where e.movement_type = 'outbound'))[1] as parcel_quote,
      string_agg(distinct e.invoice_reference, ', ') as references_list
    from public.andreani_billing_entries e
    where e.order_id = any(p_order_ids)
    group by e.order_id
  )
  select ids.id, p.billed_outbound, p.billed_return, p.billed_exchange, p.billed_other,
    p.billed_total, coalesce(p.entries, 0), p.checkout_quote, p.parcel_quote,
    coalesce(p.parcel_quote, p.checkout_quote),
    p.billed_outbound - p.checkout_quote, p.billed_outbound - p.parcel_quote,
    public.andreani_reconciliation_status(p.billed_outbound, coalesce(p.parcel_quote, p.checkout_quote)),
    p.references_list
  from unnest(p_order_ids) as ids(id)
  left join per_order p on p.order_id = ids.id
$$;

-- 8. Resumen del dashboard ------------------------------------------------------------
-- Mismo resumen que 20261008100000; el facturado ahora sale de los cargos.
create or replace function public.admin_logistics_summary(p_from timestamptz, p_to timestamptz)
returns jsonb language sql stable security definer
set search_path = pg_catalog, public, pg_temp as $$
  with orders as (
    select o.*,
      (o.estado in ('pagado','approved','enviado','en_camino','visita_fallida','en_sucursal',
        'retiro_pendiente','retiro_vencido','en_devolucion','devuelto_beyonix','entregado')
       or o.payment_status = 'approved') and o.estado <> 'cancelado' as sold
    from public.ordenes o
    where o.created_at >= p_from and o.created_at < p_to
      and coalesce(o.shipping_provider, o.envio_proveedor) = 'andreani'
  ),
  current_parcels as (
    select pk.order_id, count(p.id)::integer as parcels
    from public.order_packages pk
    join public.order_package_parcels p on p.package_id = pk.id
      and p.attempt_number = pk.attempt_number and p.parcel_count = pk.parcel_count
    where pk.order_id in (select id from orders) and pk.parcel_count is not null
    group by pk.order_id
  ),
  reconciliation as (
    select r.* from public.andreani_order_reconciliation(
      array(select id from orders where sold)) r
  )
  select jsonb_build_object(
    'ordersCreated', count(*) filter (where o.andreani_envio_id is not null),
    'ordersSent', count(*) filter (where o.andreani_handed_over_at is not null
      or o.estado in ('enviado','en_camino','visita_fallida','en_sucursal','retiro_pendiente',
        'retiro_vencido','en_devolucion','devuelto_beyonix','entregado')),
    'ordersDelivered', count(*) filter (where o.estado = 'entregado' or o.delivered_at is not null),
    'ordersReturned', count(*) filter (where o.estado in ('en_devolucion','devuelto_beyonix')
      or exists (select 1 from public.order_claims c where c.order_id = o.id and c.cancelled_at is null)),
    'parcels', coalesce(sum(cp.parcels), 0),
    'soldOrders', count(*) filter (where o.sold),
    'snapshotOrders', count(*) filter (where o.sold and o.shipping_provider_quote_amount is not null),
    'chargedToCustomers', coalesce(sum(o.shipping_cost_charged) filter (where o.sold), 0),
    'providerQuoted', coalesce(sum(o.shipping_provider_quote_amount) filter (where o.sold), 0),
    'markupCollected', coalesce(sum(o.shipping_markup_amount) filter (where o.sold), 0),
    'roundingAdjustment', coalesce(sum(o.shipping_rounding_amount) filter (where o.sold), 0),
    'benefitAbsorbed', coalesce(sum(coalesce(o.shipping_benefit_amount,
      greatest(coalesce(o.shipping_cost_real, 0) - coalesce(o.shipping_cost_charged, 0), 0)))
      filter (where o.sold), 0),
    'parcelQuoted', coalesce(sum(o.shipping_parcel_quote_amount) filter (where o.sold
      and o.shipping_parcel_quote_status = 'quoted'), 0),
    'parcelQuotedOrders', count(*) filter (where o.sold and o.shipping_parcel_quote_status = 'quoted'),
    'parcelQuoteDifference', coalesce(sum(o.shipping_parcel_quote_amount - o.shipping_provider_quote_amount)
      filter (where o.sold and o.shipping_parcel_quote_status = 'quoted'
        and o.shipping_provider_quote_amount is not null), 0),
    'parcelQuoteComparableOrders', count(*) filter (where o.sold and o.shipping_parcel_quote_status = 'quoted'
      and o.shipping_provider_quote_amount is not null),
    'comparableProviderQuoted', coalesce(sum(o.shipping_provider_quote_amount)
      filter (where o.sold and o.shipping_parcel_quote_status = 'quoted'
        and o.shipping_provider_quote_amount is not null), 0),
    'billedByAndreani', coalesce((select sum(r.billed_total) from reconciliation r), 0),
    'billedOutbound', coalesce((select sum(r.billed_outbound) from reconciliation r), 0),
    'billedReturnsAndExchanges', coalesce((select sum(coalesce(r.billed_return, 0) + coalesce(r.billed_exchange, 0)
      + coalesce(r.billed_other, 0)) from reconciliation r), 0),
    'billedOrders', (select count(*) from reconciliation r where r.entries > 0),
    'billedDifferenceVsCheckout', coalesce((select sum(r.difference_checkout) from reconciliation r), 0),
    'billedDifferenceVsCheckoutOrders', (select count(*) from reconciliation r where r.difference_checkout is not null),
    'billedDifferenceVsParcel', coalesce((select sum(r.difference_parcel) from reconciliation r), 0),
    'billedDifferenceVsParcelOrders', (select count(*) from reconciliation r where r.difference_parcel is not null),
    'reconciledOrders', (select count(*) from reconciliation r where r.status = 'reconciled'),
    'minorDifferenceOrders', (select count(*) from reconciliation r where r.status = 'minor_difference'),
    'majorDifferenceOrders', (select count(*) from reconciliation r where r.status = 'major_difference'),
    'noReferenceOrders', (select count(*) from reconciliation r where r.status = 'no_reference'),
    'pendingReconciliationOrders', (select count(*) from reconciliation r where r.status = 'pending'),
    'unmatchedEntries', (select count(*) from public.andreani_billing_entries e
      where e.match_status = 'unmatched'
        and e.billed_on >= (p_from at time zone 'America/Argentina/Buenos_Aires')::date
        and e.billed_on < (p_to at time zone 'America/Argentina/Buenos_Aires')::date),
    'unmatchedAmount', coalesce((select sum(e.billed_amount) from public.andreani_billing_entries e
      where e.match_status = 'unmatched'
        and e.billed_on >= (p_from at time zone 'America/Argentina/Buenos_Aires')::date
        and e.billed_on < (p_to at time zone 'America/Argentina/Buenos_Aires')::date), 0),
    'thresholds', public.andreani_reconciliation_thresholds()
  )
  from orders o
  left join current_parcels cp on cp.order_id = o.id
$$;

revoke all on function public.assert_logistics_admin(uuid),
  public.andreani_billing_match(text),
  public.record_andreani_billing_entries(jsonb, text, uuid, boolean),
  public.update_andreani_billing_entry(bigint, jsonb, text, uuid),
  public.andreani_order_reconciliation(bigint[]),
  public.admin_logistics_summary(timestamptz, timestamptz)
  from public, anon, authenticated;
grant execute on function public.record_andreani_billing_entries(jsonb, text, uuid, boolean),
  public.update_andreani_billing_entry(bigint, jsonb, text, uuid),
  public.andreani_order_reconciliation(bigint[]),
  public.admin_logistics_summary(timestamptz, timestamptz)
  to service_role;

notify pgrst, 'reload schema';
